### PR TITLE
Rerun on "failed to start due to preemption". Closes #2970

### LINKED ISSUE #2970: Add new retryable case: JES error code 2.  Message: Instance failed to start due to preemption.
There’s a new response from JES that should be retryable: 
JES error code 2.  Message: Instance failed to start due to preemption.” 

THE CATCH: Henry chatted with Google, and it sounds like JES error code 2 isn’t *always* about preemption. (But in the past few weeks we’ve had a handful of cloud workflows failing each day from this response, always with the message about preemption). So to be safe, we want to make this one retryable based on the combination of the code + the message. 

Example: 
UUID: 7da0394b-371f-4fdb-ae70-737833c4fbfa
OPERATION_ID: operations/EKmIx96ALBjh373VhLH0ui8gkYad9-AKKg9wcm9kdWN0aW9uUXVldWU

Relevant workflow metadata: 
"failures"
: [
{
"causedBy": [],
"message": "Task PairedEndSingleSampleWorkflow.CollectUnsortedReadgroupBamQualityMetrics:2:1 failed. JES error code 2.  Message: Instance failed to start due to preemption."
}
],

### PR DESCRIPTION
**Pull request by cjllanwarne**
See #2970 for the current error case which we now think should be treated as preemptible.

### CODE REVIEW

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala [hunk 1]
```diff
@@ -51,12 +51,16 @@ object RunStatus {
...
-        Preempted(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
-      } else if (errorCode == Status.CANCELLED) {
-        Cancelled(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
-      } else {
-        Failed(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
+
+      errorCode match {
+        case Status.ABORTED if jesCode.contains(JesAsyncBackendJobExecutionActor.JesPreemption) =>
+          Preempted(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
+        case Status.UNKNOWN if errorMessage.exists(_.contains("failed to start due to preemption")) =>
```
Comment (mcovarr) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala]: why does the one above get a constant and not this one?

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala [hunk 2]
```diff
@@ -51,12 +51,16 @@ object RunStatus {
...
+          Preempted(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
+        case Status.CANCELLED =>
+          Cancelled(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
+        case _ =>
+          Failed(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
       }
```
Comment (mcovarr) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala]: Even DRYer, arguably more readable:
```scala
val unsuccessfulStatusBuilder = errorCode match {
  case Status.ABORTED if jesCode.contains(JesAsyncBackendJobExecutionActor.JesPreemption) => Preempted
  case Status.UNKNOWN if errorMessage.exists(_.contains("failed to start due to preemption")) => Preempted
  case Status.CANCELLED => Cancelled
  case _ => Failed
}
unsuccessfulStatusBuilder.apply(errorCode, jesCode, errorMessage, eventList, machineType, zone, instanceName)
```

File: supportedBackends/jes/src/test/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActorSpec.scala [hunk 3]
```diff
@@ -196,9 +196,9 @@ class JesAsyncBackendJobExecutionActorSpec extends TestKitSuite("JesAsyncBackend
     system.actorOf(Props(new ExecuteOrRecoverActor), "ExecuteOrRecoverActor-" + UUID.randomUUID)
   }
 
-  private def runAndFail(previousPreemptions: Int, previousUnexpectedRetries: Int, preemptible: Int, errorCode: Status, innerErrorCode: Int, expectPreemptible: Boolean): BackendJobExecutionResponse = {
+  private def runAndFail(previousPreemptions: Int, previousUnexpectedRetries: Int, preemptible: Int, errorCode: Status, innerErrorMessage: String, expectPreemptible: Boolean): BackendJobExecutionResponse = {
 
-    val runStatus = UnsuccessfulRunStatus(errorCode, Option(s"$innerErrorCode: I seen some things man"), Seq.empty, Option("fakeMachine"), Option("fakeZone"), Option("fakeInstance"))
```
Comment (mcovarr) [inline supportedBackends/jes/src/test/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActorSpec.scala]: 😢

Comment (cjllanwarne) [reply supportedBackends/jes/src/test/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActorSpec.scala]: 🙈

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala (hunk 1 above)
Comment (cjllanwarne) [reply supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala]: It's because the one above is a JES error code (ie an `Integer`) whereas this one is just a portion of an error message `String`. I can make it a constant if you prefer?

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala (hunk 2 above)
Comment (cjllanwarne) [reply supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/RunStatus.scala]: Is this an acceptable compromise? I find it more obvious what's happening:
```scala
case Status.CANCELLED => Cancelled.apply _
```
