### PR TITLE
25_hotfix Update custom_labels closes #2067

### LINKED ISSUE #2067: cromwell failing process workflows after restart
I was running a bunch of workflows (same wdl, same method) when we had to restart and redeploy cromwell service and I got Errors with no visible message, when we dug into the cromwell metadata we discovered this message that Cris interpreted as a restart issue.
message": "Workflow input processing failed:\nWorkflow contains invalid labels JSON: Unexpected end-of-input at input index 0 (line 1, position 1), expected JSON Value:\n\n^\n"

### PR DESCRIPTION
**Pull request by ruchim**
Replace "" with "{}" in the custom_labels column of the workflow_store_entry table.

### CODE REVIEW

File: database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+UPDATE WORKFLOW_STORE_ENTRY
+SET CUSTOM_LABELS = "{}"
+WHERE CUSTOM_LABELS = "";
```
Comment (mcovarr) [inline database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql]: is it currently empty or null?

also \n

File: database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
+                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd">
+
+
+    <changeSet author="rmunshi" id="replace_empty_custom_labels" dbms="mysql">
+        <sqlFile relativeToChangelogFile="true" path="migration/workflow_store/replace_empty_custom_labels.sql" />
+    </changeSet>
+
+</databaseChangeLog>
```
Comment (mcovarr) [inline database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml]: \n

File: database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql (hunk 1 above)
Comment (ruchim) [inline database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql]: I believe it is currently empty. I tested these changes against a 24 db with workflows in flight and things looked good.

Comment (cjllanwarne) [inline database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql]: I think this SQL step might be unnecessary though. As @mcovarr points out, I don't think this matches anything with `NULL`, but it doesn't matter because when you apply the default in the next migration step, everything gets that default applied.

Have you tried running the migration without this `replace_empty_custom_labels` step?

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala [hunk 3]
```diff
@@ -30,11 +30,17 @@ object SqlConverters {
   }
 
   implicit class StringOptionToClobOption(val strOption: Option[String]) extends AnyVal {
-    def toClob: Option[Clob] = strOption.flatMap(_.toClob)
+    def toClob: Option[Clob] = strOption.flatMap(_.toClobOption)
```
Comment (cjllanwarne) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: surely `def toClobOption`?

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala [hunk 4]
```diff
@@ -30,11 +30,17 @@ object SqlConverters {
...
   }
 
   implicit class StringToClobOption(val str: String) extends AnyVal {
-    def toClob: Option[Clob] = if (str.isEmpty) None else Option(new SerialClob(str.toCharArray))
+    def toClobOption: Option[Clob] = if (str.isEmpty) None else Option(new SerialClob(str.toCharArray))
+
+    def toClob(default: String): Clob = {
+      require(default.nonEmpty, "An empty string has been passed in where a non-empty default string is required to convert String objects to Clob.")
+      if(str.isEmpty) new SerialClob(default.toCharArray) else new SerialClob(str.toCharArray)
```
Comment (kshakir) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: Add a space between `if(`.

Additionally, a ToL alternative:
```scala
val data = if (str.nonEmpty) str else default
new SerialClob(data.toCharArray)
```

Same goes for the `toBlob` below.

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala [hunk 5]
```diff
@@ -30,11 +30,17 @@ object SqlConverters {
...
-    def toClob: Option[Clob] = strOption.flatMap(_.toClob)
+    def toClob: Option[Clob] = strOption.flatMap(_.toClobOption)
   }
 
   implicit class StringToClobOption(val str: String) extends AnyVal {
-    def toClob: Option[Clob] = if (str.isEmpty) None else Option(new SerialClob(str.toCharArray))
+    def toClobOption: Option[Clob] = if (str.isEmpty) None else Option(new SerialClob(str.toCharArray))
+
+    def toClob(default: String): Clob = {
+      require(default.nonEmpty, "An empty string has been passed in where a non-empty default string is required to convert String objects to Clob.")
```
Comment (cjllanwarne) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: Is this where people were asking for the `String Refined NonEmpty`? `require` will just throw an exception otherwise IIRC

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala (hunk 4 above)
Comment (cjllanwarne) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: Nice use of nospace between `if(`, but others on this team tend to disagree so, for consistency, probably best to add it... 😢

File: engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala [hunk 6]
```diff
@@ -56,7 +56,7 @@ case class SqlWorkflowStore(sqlDatabase: WorkflowStoreSqlDatabase) extends Workf
       workflowStoreEntry.workflowDefinition.toRawString,
       workflowStoreEntry.workflowInputs.toRawString,
       workflowStoreEntry.workflowOptions.toRawString,
-      workflowStoreEntry.customLabels.toRawString,
+      workflowStoreEntry.customLabels.toString,
```
Comment (cjllanwarne) [inline engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala]: ToL: Consider me surprised! I didn't think `toString` on `Clob` would work!

File: engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala [hunk 7]
```diff
@@ -68,13 +68,13 @@ case class SqlWorkflowStore(sqlDatabase: WorkflowStoreSqlDatabase) extends Workf
...
     WorkflowStoreEntry(
       workflowExecutionUuid = WorkflowId.randomId().toString,
-      workflowDefinition = workflowSourceFiles.wdlSource.toClob,
-      workflowInputs = workflowSourceFiles.inputsJson.toClob,
-      workflowOptions = workflowSourceFiles.workflowOptionsJson.toClob,
-      customLabels = workflowSourceFiles.labelsJson.toClob,
+      workflowDefinition = workflowSourceFiles.wdlSource.toClobOption,
+      workflowInputs = workflowSourceFiles.inputsJson.toClobOption,
+      workflowOptions = workflowSourceFiles.workflowOptionsJson.toClobOption,
+      customLabels = workflowSourceFiles.labelsJson.toClob("{}"),
```
Comment (cjllanwarne) [inline engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala]: This was a little confusing on skim-reading. Could you make it `...toClob(default = "{}")` for the benefit of Future Chris?

File: services/src/test/scala/cromwell/services/ServicesStoreSpec.scala [hunk 8]
```diff
@@ -361,8 +345,8 @@ class ServicesStoreSpec extends FlatSpec with Matchers with ScalaFutures with St
       val emptyBlob = new SerialBlob(Array.empty[Byte])
 
       val workflowUuid = WorkflowId.randomId().toString
-      val workflowStoreEntry = WorkflowStoreEntry(workflowUuid, "{}".toClob, "{}".toClob, "{}".toClob,
-        "Testing", OffsetDateTime.now.toSystemTimestamp, Option(emptyBlob), "{}".toClob)
+      val workflowStoreEntry = WorkflowStoreEntry(workflowUuid, "{}".toClobOption, "{}".toClobOption, "{}".toClobOption,
+        "Testing", OffsetDateTime.now.toSystemTimestamp, Option(emptyBlob), "{}".toClob("{}"))
```
Comment (cjllanwarne) [inline services/src/test/scala/cromwell/services/ServicesStoreSpec.scala]: Same here with `default = `

File: .travis.yml [hunk 9]
```diff
@@ -19,7 +19,7 @@ before_install:
   - openssl aes-256-cbc -K "$encrypted_5ebd3ff04788_key" -iv "$encrypted_5ebd3ff04788_iv" -in src/bin/travis/resources/jesConf.tar.enc -out jesConf.tar -d || true
 env:
   global:
-    - CENTAUR_BRANCH=develop
+    - CENTAUR_BRANCH=4648da44fc1695d5306e9b4f05e96fa5a5cadb8f
```
Comment (cjllanwarne) [inline .travis.yml]: Remember to revert before merging? Or if this is going to be the new official `25-hotfix` centaur branch, can we label it as such?

File: database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml [hunk 10]
```diff
@@ -0,0 +1,20 @@
+<?xml version="1.0" encoding="UTF-8" standalone="no"?>
+<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
+                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd">
+
+    <property name="clob.type" value="LONGTEXT" dbms="mysql"/>
+    <property name="clob.type" value="LONGVARCHAR" dbms="hsqldb"/>
```
Comment (kshakir) [inline database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml]: The database should only be using `LONGTEXT`.

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala (hunk 4 above)
Comment (cjllanwarne) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: @kshakir see my comment below 😢

File: engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala (hunk 6 above)
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala]: Good catch. I don't think this works. Do not call `Object.toString()` on the _interface_ `Clob` or you're going to have a bad time, getting something unexpected back. `SqlConverters` needs to create a `toRawString` for `Clob`s, just like there is one for `Option[Clob]`. While there, please also add a `Blob.toBytes` implicit.

Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala]: FYI- Hurray! Centaur caught this bad call `Object.toString()`. One example of _many_:

```java
2017-03-17 17:13:01,231 cromwell-system-akka.dispatchers.engine-dispatcher-41 ERROR - WorkflowManagerActor Workflow 35d07911-6931-4d3a-91be-5007d7b83bbd failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
Workflow contains invalid labels JSON: Unexpected character 'o' at input index 0 (line 1, position 1), expected JSON Value:
org.hsqldb.jdbc.JDBCClobClient@28f51798
^
```

File: .travis.yml (hunk 9 above)
Comment (ruchim) [inline .travis.yml]: This commit was the last commit merged to Centaur before we released 25. Just waiting for the tests to pass on this commit and will update it to a proper branch if it turns out to be correct.

Comment (Horneth) [inline .travis.yml]: I though we just said at standup we wanted the commit hash in here ? xD
I'm asking for the release WDL, do people want a hash or a branch ?

File: database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml (hunk 10 above)
Comment (ruchim) [inline database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml]: I'm happy to adjust this here, but it is how clob types are defined for hsqldb all over. Perhaps that can be a future adjustment if you'd like, in the interest of time.

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala (hunk 3 above)
Comment (ruchim) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: 100%

File: engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala (hunk 6 above)
Comment (ruchim) [inline engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala]: Added more implicit conversions to the SqlConverters

File: database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql (hunk 1 above)
Comment (ruchim) [inline database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql]: When I test the migration by excluding changeset id ="custom_labels_not_null" and only keeping changeset id="custom_labels_not_null", I get an error. 
WorkflowManagerActor Workflow b5140dfb-41db-4824-b6f6-c08af1e51384 failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
Workflow contains invalid labels JSON: Unexpected end-of-input at input index 0 (line 1, position 1), expected JSON Value:

^

Comment (ruchim) [inline database/migration/src/main/resources/changesets/migration/workflow_store/replace_empty_custom_labels.sql]: When turning on the 25_hotfix against a 24 database, if I stop cromwell after the liquibase migrations finish and look at the workflow store table, if I run a query select * from workflow_store_entry where set custom_labels=NULL, I get no matches. If I try to match for empty strings "", then I can see every workflow that was running prior to the migration.

File: .travis.yml (hunk 9 above)
Comment (ruchim) [inline .travis.yml]: Hash!

File: database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml [hunk 11]
```diff
@@ -0,0 +1,20 @@
+<?xml version="1.0" encoding="UTF-8" standalone="no"?>
+<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
+                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd">
+
+    <property name="clob.type" value="LONGTEXT" dbms="mysql"/>
```
Comment (ruchim) [inline database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml]: remove 6,7 and replace clob.tybe with LONGTEXT

File: database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala [hunk 12]
```diff
@@ -29,26 +32,53 @@ object SqlConverters {
     }
   }
 
+  implicit class ClobToRawString(val clob: Clob) extends AnyVal {
+    // yes, it starts at 1
```
Comment (ruchim) [inline database/sql/src/main/scala/cromwell/database/sql/SqlConverters.scala]: move two lines down.

File: project/Dependencies.scala [hunk 13]
```diff
@@ -108,7 +109,10 @@ object Dependencies {
     "com.github.pathikrit" %% "better-files" % betterFilesV
   )
 
-  val databaseSqlDependencies = baseDependencies ++ slickDependencies ++ dbmsDependencies
+  val databaseSqlDependencies = baseDependencies ++ slickDependencies ++ dbmsDependencies ++ List(
```
Comment (ruchim) [inline project/Dependencies.scala]: rename the refined dependencies list

File: database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml (hunk 11 above)
Comment (ruchim) [inline database/migration/src/main/resources/changesets/replace_empty_custom_labels.xml]: done

**Comment by kshakir** [comment]
👍

**Comment by cjllanwarne** [comment]
👍
