### PR TITLE
Update better-files to 3.8.0 to fix a bug when using zipped-import files.

### LINKED ISSUE #4969: imports zip file with a subdir causes errors
With Cromwell 41, when submitting an imports.zip containing workflow imports, if the zipfile has a subdirectory, I get these errors:

2019-05-14 11:05:38,560 cromwell-system-akka.dispatchers.engine-dispatcher-101 ERROR - WorkflowManagerActor Workflow a3fb73f1-2976-456\
3-a691-a356e2744dda failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.Materiali\
zeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
/tmp/imports_workflow_a3fb73f1-2976-4563-a691-a356e2744dda_9012613107684347004.zip7783627211874195701/tasks/tasks_assembly.wdl
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$ma\
terialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:215)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWor\
kflowDescriptorActor.scala:185)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWor\
kflowDescriptorActor.scala:180)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processE\
vent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescr\
iptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDesc\
riptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2019-05-14 11:05:38,561 cromwell-system-akka.dispatchers.engine-dispatcher-101 INFO  - WorkflowManagerActor WorkflowActor-a3fb73f1-297\
6-4563-a691-a356e2744dda is in a terminal state: WorkflowFailedState

### PR DESCRIPTION
**Pull request by rhpvorderman**
Hello all, 

This fixes BA-6144
EDIT: also fixes #4969

At LUMC we are currently creating [wdl-packager](https://github.com/biowdl/wdl-packager/tree/init). This program uses miniwdl to determine any file based imports in a WDL file and package them into a zip. This was done to make the release and deployment of BioWDL pipelines less unwieldy. Also this provides ready-made zip files for people who want to run BioWDL on a cromwell server.

When testing I discovered that [Cromwell does not properly unpack zip files](https://broadworkbench.atlassian.net/projects/BA/issues/BA-6144). Zips with nested directories can not be unpacked. This is due to a bug in better-files 2.17.1 that was fixed in 3.0.0 and higher versions.

In this PR the version of better-files is updated to 3.8.0 and any incompatibilities should be fixed.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Since a lot of the [documentation on imports](https://cromwell.readthedocs.io/en/develop/Imports/) already describes the use of zip files with nested directories I added a note to the changelog bug fixes area, so people can discover that they need to use the latest version for this behavior.

**Comment by aednichols** [comment]
Thank you for the contribution and sorry for the trouble. We will send this through review.

**Comment by rhpvorderman** [comment]
> Thank you for the contribution and sorry for the trouble. We will send this through review.

Thanks! It's no trouble at all. Cromwell (and WDL) make my life easier every single day. It's a great project. I am happy that I can make a small contribution and do something in return.

File: core/src/main/scala/cromwell/core/path/BetterFileMethods.scala [hunk 1]
```diff
@@ -494,6 +506,8 @@ object BetterFileMethods {
 
   def currentWorkingDirectory: Path = DefaultPath(better.files.File.currentWorkingDirectory.path)
 
+  def DefaultCharset: Charset = Charset.defaultCharset()
```
Comment (rhpvorderman) [inline core/src/main/scala/cromwell/core/path/BetterFileMethods.scala]: Question for the reviewer: Would a `val` be more appropriate here? defaultCharset() defaults to the system value and if it can not find it to `UTF-8`. I guess there is no value in calling it more than once, but since I was uncertain I left it as a def.

Comment (aednichols) [reply core/src/main/scala/cromwell/core/path/BetterFileMethods.scala]: Do we expect it to change its value during the lifetime of the program execution?

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,12 @@
 
 ## 48 Release Notes
 
+### Bug fixes
+
++ Fix a bug where zip files with directories could not be imported. 
+  For example a zip with `a.wdl` and `b.wdl` could be imported but one with `sub_workflows/a.wdl` 
+  and `imports/b.wdl` could not.
```
Comment (mcovarr) [inline CHANGELOG.md]: It would be nice to have a test that demonstrates this is fixed, though I'm not sure how much work that would be.

File: core/src/main/scala/cromwell/core/path/BetterFileMethods.scala (hunk 1 above)
Comment (rhpvorderman) [reply core/src/main/scala/cromwell/core/path/BetterFileMethods.scala]: Probably not. That would be quite uncommon, because it is locale related. I will make it a val.

Comment (rhpvorderman) [reply core/src/main/scala/cromwell/core/path/BetterFileMethods.scala]: Done.

File: CHANGELOG.md (hunk 2 above)
Comment (rhpvorderman) [reply CHANGELOG.md]: Well given that it is a function that I want to make the distribution of BioWDL pipelines dependent on, the amount of work is not a stopper. These zips are so much nicer than having to check out git repositories, making sure all the submodules are correctly up to date etc. Also these git repositories contain a lot of cruft from the user perspective: test files, CI stuff etc. 
I have added a test with a simple zip file created from the BioWDL QC pipeline. It turned out to be quite easy to test.

**Comment by rhpvorderman** [comment]
The dockerScripts build seems to fail due to some connection error. Hopefully it will succeed after a restart. 
I am happy that upgrading the Betterfiles dependency to a new major version release did not cause any issues in the rest of cromwell.

**Comment by aednichols** [comment]
CI passed in https://github.com/broadinstitute/cromwell/pull/5375 with same commit `
b8ac4a6`, merging
