### PR TITLE
Retry jobs that have been killed by a cluster backend. [BA-5669]

### LINKED ISSUE #4998: Regression: Cromwell does not restart externally killed jobs on the SFS backend.
Can be reproduced using the following workflow

```wdl
version 1.0

task crash {
  command <<<
    kill -9 $$
  >>>
}

workflow crash {
  call crash 
}

```
We use a configuration with the following values:
```HOCON
backend {
  default="SGE"
  providers {
    SGE {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        exit-code-timeout-seconds = 120
        default-runtime-attributes {
          maxRetries: 2
        }
      }
    }
  }
}
workflow-options {
  workflow-failure-mode = "ContinueWhilePossible"
}
```
On Cromwell 37 the workflow will be run. Jobs will be killed and retried.
On Cromwell 39, the retries will not happen any more.
This is very annoying, as our cluster kills jobs that exceed the memory limit, and some java based jobs seem to have random memory spikes. Having only 1 try means basically that a workflow with 50-100 jobs will usually fail, unless we give some jobs an insane memory parameter.

This is probably caused by the refactoring in:
https://github.com/broadinstitute/cromwell/pull/4654/files
EDIT: This statement was not meant to put a blame on someone. I understand that code needs to be refactored at times and that bugs can creep in.

I will look if I can fix the issue myself but maybe @cjllanwarne can also have a quick look? That would be much appreciated!

### PR DESCRIPTION
**Pull request by rhpvorderman**
Fixes #4998

A bit of context: We have a cluster that works using SGE and it kills jobs that use too much VMEM. This means that any java jobs get sometimes randomly killed by the cluster. These jobs do not get a proper RC file because the cluster killed them. This meant that Cromwell would be waiting eternally for the RC file.

Then my former colleague ffinfo created a new feature that assumed an externall kill of no RC file was found and the cluster reported the job as finished. #4112 . This code creates the exit file and reports the job as failed in this scenario.

The comments implied he meant to put `137` in the RC file, as that is the exit code for SIGKILL (`kill -9`) but instead  the code put the exit code `9` in there.

This code was refactored by @cjllanwarne, and 9 was changed to a variable for the exit code: SIGTERM. Which made perfect sense.

Unfortunately this broke some functionality. Jobs that are externally killed are no longer retried. This is because cromwell assumes that jobs with an exit code SIGINT(`130`), SIGKILL(`137`) or SIGTERM(`143`) are killed by cromwell, and should therefore not be restarted. This makes perfect sense. 

This PR does not change the retry behaviour of cromwell. It does change the exit code for externally (not killed by cromwell!) jobs so these can be retried.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
In order to fix the coverage I am willing to write tests. But I need some explanation on how to configure the cromwell that is used by centaur, so I can set `exit-code-timeout-seconds`. Can somebody give me that? Thanks!

File: supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala [hunk 1]
```diff
@@ -304,7 +306,11 @@ class DispatchedConfigAsyncJobExecutionActor(override val standardParams: Standa
           jobLogger.error(s"Return file not found after ${exitCodeTimeout.getOrElse(backupError)} seconds, assuming external kill")
 
           val returnCodeTemp = jobPaths.returnCode.plusExt("kill")
-          returnCodeTemp.write(s"$SIGTERM${System.lineSeparator}")
+          // If SIGTERM, SIGKILL or SIGINT codes are used, cromwell will assume the job has been aborted by cromwell.
+          // And it will therefore NOT retry the job. Which makes perfect sense. Best not to change that in the
+          // StandardAsyncExecutionActor code, but give a nonsensical return code here.
+          val exitValue = if (retryExternallyKilledJobs) Int.MaxValue else SIGKILL
+          returnCodeTemp.write(s"${exitValue}${System.lineSeparator}")
```
Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala]: I haven't checked, but I wouldn't be surprised if something like `returnCodeTemp.writeLine(exitValue)` were possible

File: supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala [hunk 2]
```diff
@@ -304,7 +306,11 @@ class DispatchedConfigAsyncJobExecutionActor(override val standardParams: Standa
           jobLogger.error(s"Return file not found after ${exitCodeTimeout.getOrElse(backupError)} seconds, assuming external kill")
 
           val returnCodeTemp = jobPaths.returnCode.plusExt("kill")
-          returnCodeTemp.write(s"$SIGTERM${System.lineSeparator}")
+          // If SIGTERM, SIGKILL or SIGINT codes are used, cromwell will assume the job has been aborted by cromwell.
+          // And it will therefore NOT retry the job. Which makes perfect sense. Best not to change that in the
+          // StandardAsyncExecutionActor code, but give a nonsensical return code here.
+          val exitValue = if (retryExternallyKilledJobs) Int.MaxValue else SIGKILL
```
Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala]: This check looks redundant - you'll only get here if the `exitCodeTimeout` is defined, and that's the exact same condition as `retryExternallyKilledJobs `.

Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala]: Not overloading `SIGKILL` et al sounds sensible but I'd still suggest staying without the usual exit code range. Per http://tldp.org/LDP/abs/html/exitcodes.html:
> An exit value greater than 255 returns an exit code modulo 256

In this case, `2,147,483,647 mod 256 = 255`(!!)

The same page has this suggestion (and this seems sensible to me too):
> The author of this document proposes restricting user-defined exit codes to the range 64 - 113

File: supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala (hunk 1 above)
Comment (rhpvorderman) [reply supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala]: Yes it is possible. It is called `appendLine` apparently. From cromwell.core.path.BetterFileMethods.
Will implement

File: supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala (hunk 2 above)
Comment (rhpvorderman) [reply supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala]: :+1: I was tempted to put this in, in case we wanted to make it configurable if jobs should fail when externally killed. But expanding the code base for 'just in case' reasons is bad practice. Will remove this.

**Comment by rhpvorderman** [comment]
@cjllanwarne Thanks for your great suggestions.
The change has been brought back to one line of code. And 7 lines of comments to explain why that line is the way it is... Hopefully the last line will make clear why `79` is an appropriate exit code for this use case.

**Comment by cjllanwarne** [comment]
This now looks good to me. I'll make a clone of this branch in our repo so that our tests can run on it (it's a permissions thing that means only internal PRs can run the full suite of CI... 🤷‍♂)

**Comment by rhpvorderman** [comment]
>  I'll make a clone of this branch in our repo so that our tests can run on it (it's a permissions thing that means only internal PRs can run the full suite of CI... man_shrugging)

Thanks!

**Comment by rhpvorderman** [comment]
> We don't actively test the cluster backend retries, which I think adequately explains why the codecov for this diff is 0.

 >   In other words, the tests don't cover this code because we never use it, but if it works for you then +1 from me.

Thanks a lot @cjllanwarne ! I have thought about setting up tests in the cromwell test suite, but it is not very easy (if it all possible) to do this in an automated fashion.
We regularly test our workflows on the cluster, so any issues with Cromwell are bound to come up quickly. 
Thanks again for reviewing and merging!
