### PR TITLE
Run Finalize Actor even if workflow execution fails Closes #912

### LINKED ISSUE #912: WorkflowFinalizationActor is not run if the workflow fails during execution

### PR DESCRIPTION
**Pull request by Horneth**
- Removes the ability to abort Finalization Actor

- Ensures that the finalization actor runs if the Workflow reaches the `Initialize` state, regardless of what happens next (failure, success, abort), or when it happens (initialization, execution).

### CODE REVIEW

File: engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala [hunk 1]
```diff
@@ -185,8 +185,9 @@ final case class WorkflowExecutionActor(workflowId: WorkflowId,
       context.actorOf(actorProps, buildJobExecutionActorName(jobDescriptor)) ! ExecuteJobCommand
       stay() using mergeExecutionDiff(stateData, WorkflowExecutionDiff(Map(jobDescriptor.key -> ExecutionStatus.Running)))
     case Event(BackendJobPreparationFailed(jobKey, t), stateData) =>
-      log.error(s"Failed to start job $jobKey", t)
+      log.error(t, "Failed to start job {}", jobKey) // TODO: This log is a candidate for removal. It's now recorded in metadata
```
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala]: Favor, only if you end up making other changes: Do you mind expanding `t` to `thowable`?

**Comment by kshakir** [comment]
👍

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 2]
```diff
@@ -107,10 +108,10 @@ object WorkflowActor {
     * @param currentLifecycleStateActor The current lifecycle stage, represented by an ActorRef.
     */
   case class WorkflowActorData(currentLifecycleStateActor: Option[ActorRef],
-                               workflowDescriptor: Option[EngineWorkflowDescriptor])
+                               workflowDescriptor: Option[EngineWorkflowDescriptor],
+                               executionResponse: Option[WorkflowExecutionActorResponse])
   object WorkflowActorData {
-    def empty = WorkflowActorData(None, None)
-    def apply(currentLifecycleStateActor: ActorRef, workflowDescriptor: EngineWorkflowDescriptor): WorkflowActorData = WorkflowActorData(Option(currentLifecycleStateActor), Option(workflowDescriptor))
+    def empty = WorkflowActorData(None, None, None)
```
Comment (scottfrazer) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: totally thinking out loud here... maybe this would be more clear as named parameters or default parameter values on the case class

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 3]
```diff
@@ -158,17 +159,17 @@ class WorkflowActor(workflowId: WorkflowId,
...
-      goto(InitializingWorkflowState) using WorkflowActorData(initializerActor, workflowDescriptor)
+      goto(InitializingWorkflowState) using data.copy(currentLifecycleStateActor = Option(initializerActor), workflowDescriptor = Option(workflowDescriptor))
     case Event(MaterializeWorkflowDescriptorFailureResponse(reason: Throwable), _) =>
       context.parent ! WorkflowFailedResponse(workflowId, MaterializingWorkflowDescriptorState, Seq(reason))
       goto(WorkflowFailedState)
   }
 
   when(InitializingWorkflowState) {
-    case Event(WorkflowInitializationSucceededResponse, WorkflowActorData(_, Some(workflowDescriptor))) =>
+    case Event(WorkflowInitializationSucceededResponse, data@WorkflowActorData(_, Some(workflowDescriptor), _)) =>
```
Comment (scottfrazer) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: just curious... why was the `data@` added?

Comment (scottfrazer) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: Oh I see, nevermind

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 4]
```diff
@@ -178,28 +179,41 @@ class WorkflowActor(workflowId: WorkflowId,
...
+      }
+    case Event(WorkflowFinalizationFailedResponse(finalizationFailures), data) =>
+      data.executionResponse match {
+        case Some(WorkflowExecutionFailedResponse(executionFailures)) =>
+          context.parent ! WorkflowFailedResponse(workflowId, FinalizingWorkflowState, executionFailures ++ finalizationFailures)
+        case Some(WorkflowExecutionSucceededResponse) =>
+          context.parent ! WorkflowFailedResponse(workflowId, FinalizingWorkflowState, finalizationFailures)
+        case None =>
+          context.parent ! WorkflowFailedResponse(workflowId, FinalizingWorkflowState, List(new IllegalStateException(s"Workflow $workflowId at Finalize stage without execution result.")))
+      }
```
Comment (scottfrazer) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: Since I didn't add the 'abort' case here... is it easy to add that to your PR after mine is merged in?

**Comment by scottfrazer** [comment]
👍  -- though it'd be nice to add the abort case too

**Comment by Horneth** [comment]
Please re-review

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 5]
```diff
@@ -24,71 +23,106 @@ class WorkflowActorSpec extends CromwellTestkitSpec with WorkflowDescriptorBuild
...
+  "WorkflowActor" should {
+
+    "run Finalization actor if Initialization fails" in {
+      val actor = createWorkflowActor(InitializingWorkflowState)
+
+      EventFilter.info(pattern = "transitioning from FinalizingWorkflowState to WorkflowFailedState", occurrences = 1).intercept {
+        within(CromwellTestkitSpec.timeoutDuration) {
+          actor ! WorkflowInitializationFailedResponse(Seq(new Exception("Materialization Failed")))
+        }
+      }
```
Comment (kshakir) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: I believe the `within` block should go outside the `EventFilter.info` block. Here, the `within` is only guaranteeing that the tell returns within the timeout.

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 6]
```diff
@@ -24,71 +23,106 @@ class WorkflowActorSpec extends CromwellTestkitSpec with WorkflowDescriptorBuild
...
+
+      actor.stop()
+    }
+
+    "not run Finalization actor if aborted when in MaterializingWorkflowDescriptorState" in {
+      val actor = createWorkflowActor(MaterializingWorkflowDescriptorState)
+
+      EventFilter.info(pattern = "transitioning from MaterializingWorkflowDescriptorState to WorkflowAbortedState", occurrences = 1).intercept {
+        within(CromwellTestkitSpec.timeoutDuration) {
```
Comment (kshakir) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: Same thing for most of the other `within`s above.

**Comment by kshakir** [comment]
re-👍  after comments addressed

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 7]
```diff
@@ -178,33 +184,43 @@ class WorkflowActor(workflowId: WorkflowId,
...
+        case StateCheckpoint(WorkflowAbortingState, None) =>
+          context.parent ! WorkflowAbortedResponse(workflowId)
+          WorkflowAbortedState
+        case StateCheckpoint(state, Some(failures)) =>
+          context.parent ! WorkflowFailedResponse(workflowId, state, failures)
+          WorkflowFailedState
+        case StateCheckpoint(state, None) =>
+          context.parent ! WorkflowSucceededResponse(workflowId)
+          WorkflowSucceededState
+      }
```
Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: perhaps pull this out to a method?
