### PR TITLE
Fix packed CWL bug

### LINKED ISSUE #4103: enable parsing of packed cwl containing `SchemaDefRequirement` with multiple `$import:`
I am attempting to run a packed CWL workflow.

The output from the latest cromwell is:
```
(p3cwl) [jeremiah@localhost ~]$ git clone https://github.com/NCI-GDC/gdc-dnaseq-cwl.git
(p3cwl) [jeremiah@localhost ~]$ java -jar cromwell/server/target/scala-2.12/cromwell-35-fd560e9-SNAP.jar run gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl --inputs gdc-dnaseq-cwl/workflows/bamfastq_align/transform_c9bab596-0b03-4066-b428-d9cd36fb1c.yml --type CWL --workflow-root main
[2018-09-14 13:19:10,55] [info] Running with database db.url = jdbc:hsqldb:mem:d07a09a8-8d20-4095-967b-c6f375a3f309;shutdown=false;hsqldb.tx=mvcc
[2018-09-14 13:19:19,53] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-09-14 13:19:19,55] [info] [RenameWorkflowOptionsInMetadata] 100%
[2018-09-14 13:19:19,67] [info] Running with database db.url = jdbc:hsqldb:mem:e41fe9de-508c-4f49-aeaa-ce7474d7c1e2;shutdown=false;hsqldb.tx=mvcc
[2018-09-14 13:19:20,18] [info] Slf4jLogger started
[2018-09-14 13:19:20,25] [info] Pre Processing Workflow...
[2018-09-14 13:19:20,65] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl
[2018-09-14 13:19:54,70] [info] Pre Processing Inputs...
[2018-09-14 13:19:54,94] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-89ab52b",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2018-09-14 13:19:55,04] [info] Metadata summary refreshing every 2 seconds.
[2018-09-14 13:19:55,31] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-09-14 13:19:55,32] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-09-14 13:19:55,32] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2018-09-14 13:19:56,83] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2018-09-14 13:19:56,88] [info] SingleWorkflowRunnerActor: Version 35-fd560e9-SNAP
[2018-09-14 13:19:56,91] [info] SingleWorkflowRunnerActor: Submitting workflow
[2018-09-14 13:19:57,89] [info] CWL (Unspecified version) workflow caab4283-a3d4-4966-85ba-56d0992c8f00 submitted
[2018-09-14 13:19:57,90] [info] SingleWorkflowRunnerActor: Workflow submitted caab4283-a3d4-4966-85ba-56d0992c8f00
[2018-09-14 13:19:57,91] [info] 1 new workflows fetched
[2018-09-14 13:19:57,92] [info] WorkflowManagerActor Starting workflow caab4283-a3d4-4966-85ba-56d0992c8f00
[2018-09-14 13:19:57,93] [warn] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2018-09-14 13:19:57,96] [info] WorkflowManagerActor Successfully started WorkflowActor-caab4283-a3d4-4966-85ba-56d0992c8f00
[2018-09-14 13:19:57,96] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2018-09-14 13:19:57,96] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2018-09-14 13:19:58,11] [info] MaterializeWorkflowDescriptorActor [caab4283]: Parsing workflow as CWL v1.0
[2018-09-14 13:20:00,08] [error] WorkflowManagerActor Workflow caab4283-a3d4-4966-85ba-56d0992c8f00 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Custom type file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroup_fastq_pe_file was referred to but not found in schema def Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#amplicon_kit.yml/amplicon_kit_set_file,Some([Lcwl.InputRecordField;@5f7affaf),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#amplicon_kit.yml/amplicon_kit_set_uuid,Some([Lcwl.InputRecordField;@4e2399d2),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#capture_kit.yml/capture_kit_set_file,Some([Lcwl.InputRecordField;@74284741),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#capture_kit.yml/capture_kit_set_uuid,Some([Lcwl.InputRecordField;@7f378344),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroup_meta,Some([Lcwl.InputRecordField;@77389c8a),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroup_fastq_pe_file,Some([Lcwl.InputRecordField;@258776b6),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroup_fastq_se_file,Some([Lcwl.InputRecordField;@13a32f08),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroups_bam_file,Some([Lcwl.InputRecordField;@50cda39b),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroup_fastq_pe_uuid,Some([Lcwl.InputRecordField;@63a2b9c4),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroup_fastq_se_uuid,Some([Lcwl.InputRecordField;@7d8e51c0),record,None)), Inl(InputRecordSchema(file:///home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform_pack.cwl#readgroup.yml/readgroups_bam_uuid,Some([Lcwl.InputRecordField;@775ffa16),record,None)).
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2018-09-14 13:20:00,08] [info] WorkflowManagerActor WorkflowActor-caab4283-a3d4-4966-85ba-56d0992c8f00 is in a terminal state: WorkflowFailedState
[2018-09-14 13:20:00,92] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2018-09-14 13:20:05,34] [info] Workflow polling stopped
[2018-09-14 13:20:05,36] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2018-09-14 13:20:05,36] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2018-09-14 13:20:05,37] [info] Aborting all running workflows.
[2018-09-14 13:20:05,39] [info] WorkflowStoreActor stopped
[2018-09-14 13:20:05,36] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2018-09-14 13:20:05,39] [info] JobExecutionTokenDispenser stopped
[2018-09-14 13:20:05,40] [info] WorkflowLogCopyRouter stopped
[2018-09-14 13:20:05,40] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2018-09-14 13:20:05,40] [info] WorkflowManagerActor All workflows finished
[2018-09-14 13:20:05,40] [info] WorkflowManagerActor stopped
[2018-09-14 13:20:05,40] [info] Connection pools shut down
[2018-09-14 13:20:05,41] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2018-09-14 13:20:05,41] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2018-09-14 13:20:05,41] [info] SubWorkflowStoreActor stopped
[2018-09-14 13:20:05,41] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2018-09-14 13:20:05,41] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2018-09-14 13:20:05,42] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2018-09-14 13:20:05,42] [info] JobStoreActor stopped
[2018-09-14 13:20:05,42] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2018-09-14 13:20:05,42] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2018-09-14 13:20:05,42] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2018-09-14 13:20:05,43] [info] CallCacheWriteActor stopped
[2018-09-14 13:20:05,43] [info] DockerHashActor stopped
[2018-09-14 13:20:05,43] [info] IoProxy stopped
[2018-09-14 13:20:05,43] [info] KvWriteActor Shutting down: 0 queued messages to process
[2018-09-14 13:20:05,43] [info] ServiceRegistryActor stopped
[2018-09-14 13:20:05,47] [info] Database closed
[2018-09-14 13:20:05,47] [info] Stream materializer shut down
[2018-09-14 13:20:05,48] [info] WDL HTTP import resolver closed
Workflow caab4283-a3d4-4966-85ba-56d0992c8f00 transitioned to state Failed
(p3cwl) [jeremiah@localhost ~]$ 
```

The non-packed CWL is parsed successfully:
```
(p3cwl) [jeremiah@localhost ~]$ java -jar cromwell/server/target/scala-2.12/cromwell-35-fd560e9-SNAP.jar run gdc-dnaseq-cwl/workflows/bamfastq_align/transform.cwl --inputs gdc-dnaseq-cwl/workflows/bamfastq_align/transform_c9bab596-0b03-4066-b428-dda9cd36fb1c.yml --type CWL
[2018-09-14 13:21:06,87] [info] Running with database db.url = jdbc:hsqldb:mem:ff56e263-4418-491e-afa7-b92aee80129e;shutdown=false;hsqldb.tx=mvcc
[2018-09-14 13:21:16,28] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-09-14 13:21:16,30] [info] [RenameWorkflowOptionsInMetadata] 100%
[2018-09-14 13:21:16,42] [info] Running with database db.url = jdbc:hsqldb:mem:66ab1a18-96ee-4819-a2d2-f0e00fbd9b0d;shutdown=false;hsqldb.tx=mvcc
[2018-09-14 13:21:16,95] [info] Slf4jLogger started
[2018-09-14 13:21:17,05] [info] Pre Processing Workflow...
[2018-09-14 13:21:17,25] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/transform.cwl
[2018-09-14 13:21:43,20] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/fastq_clean_pe.cwl
[2018-09-14 13:21:43,34] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/fastq_cleaner_pe.cwl
[2018-09-14 13:21:43,45] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/emit_readgroup_fastq_pe_file.cwl
[2018-09-14 13:21:43,50] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/json_to_sqlite.cwl
[2018-09-14 13:21:43,56] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/fastq_clean_se.cwl
[2018-09-14 13:21:43,65] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/fastq_cleaner_se.cwl
[2018-09-14 13:21:43,70] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/emit_readgroup_fastq_se_file.cwl
[2018-09-14 13:21:43,76] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/merge_sqlite.cwl
[2018-09-14 13:21:43,83] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/readgroups_bam_to_readgroups_fastq_lists.cwl
[2018-09-14 13:21:44,04] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/biobambam2_bamtofastq.cwl
[2018-09-14 13:21:44,22] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/bam_readgroup_to_json.cwl
[2018-09-14 13:21:44,31] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/decider_readgroup_expression.cwl
[2018-09-14 13:21:44,38] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/readgroup_fastq_pe.cwl
[2018-09-14 13:21:44,45] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/emit_json_readgroup_meta.cwl
[2018-09-14 13:21:44,65] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/readgroup_fastq_se.cwl
[2018-09-14 13:21:44,79] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/merge_pe_fastq_records.cwl
[2018-09-14 13:21:44,87] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/merge_se_fastq_records.cwl
[2018-09-14 13:21:44,95] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/bwa_pe.cwl
[2018-09-14 13:21:45,21] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/fastqc.cwl
[2018-09-14 13:21:45,38] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/fastqc_db.cwl
[2018-09-14 13:21:45,46] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/fastqc_basicstatistics_json.cwl
[2018-09-14 13:21:45,54] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/bwa_record_pe.cwl
[2018-09-14 13:21:45,68] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/readgroup_json_db.cwl
[2018-09-14 13:21:45,75] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/bwa_se.cwl
[2018-09-14 13:21:45,98] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/bwa_record_se.cwl
[2018-09-14 13:21:46,12] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_mergesamfiles_aoa.cwl
[2018-09-14 13:21:46,27] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/bam_reheader.cwl
[2018-09-14 13:21:46,35] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/conditional_markduplicates.cwl
[2018-09-14 13:21:46,43] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_markduplicates.cwl
[2018-09-14 13:21:46,53] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_markduplicates_to_sqlite.cwl
[2018-09-14 13:21:46,62] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/conditional_bamindex.cwl
[2018-09-14 13:21:46,71] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_index.cwl
[2018-09-14 13:21:46,80] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/touch.cwl
[2018-09-14 13:21:46,86] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/emit_file_format.cwl
[2018-09-14 13:21:46,90] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/decider_conditional_bams.cwl
[2018-09-14 13:21:46,98] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/gatk4_baserecalibrator.cwl
[2018-09-14 13:21:47,07] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/gatk4_applybqsr.cwl
[2018-09-14 13:21:47,16] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_validatesamfile.cwl
[2018-09-14 13:21:47,29] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_validatesamfile_to_sqlite.cwl
[2018-09-14 13:21:47,37] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/metrics.cwl
[2018-09-14 13:21:48,03] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/amplicon_metrics.cwl
[2018-09-14 13:21:48,15] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collecttargetedpcrmetrics.cwl
[2018-09-14 13:21:48,38] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collecttargetedpcrmetrics_to_sqlite.cwl
[2018-09-14 13:21:48,46] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/exome_metrics.cwl
[2018-09-14 13:21:48,59] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collecthsmetrics.cwl
[2018-09-14 13:21:48,81] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collecthsmetrics_to_sqlite.cwl
[2018-09-14 13:21:48,89] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/gatk4_getpileupsummaries.cwl
[2018-09-14 13:21:48,96] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/gatk4_calculatecontamination.cwl
[2018-09-14 13:21:49,02] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/gatk_calculatecontamination_to_sqlite.cwl
[2018-09-14 13:21:49,10] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collectmultiplemetrics.cwl
[2018-09-14 13:21:49,31] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collectmultiplemetrics_to_sqlite.cwl
[2018-09-14 13:21:49,48] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collectoxogmetrics.cwl
[2018-09-14 13:21:49,59] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collectoxogmetrics_to_sqlite.cwl
[2018-09-14 13:21:49,69] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collectwgsmetrics.cwl
[2018-09-14 13:21:49,78] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/picard_collectwgsmetrics_to_sqlite.cwl
[2018-09-14 13:21:49,87] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_flagstat.cwl
[2018-09-14 13:21:49,94] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_flagstat_to_sqlite.cwl
[2018-09-14 13:21:50,02] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_idxstats.cwl
[2018-09-14 13:21:50,08] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_idxstats_to_sqlite.cwl
[2018-09-14 13:21:50,17] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_stats.cwl
[2018-09-14 13:21:50,38] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/samtools_stats_to_sqlite.cwl
[2018-09-14 13:21:50,46] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/workflows/bamfastq_align/integrity.cwl
[2018-09-14 13:21:50,64] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/ls_l.cwl
[2018-09-14 13:21:50,71] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/md5sum.cwl
[2018-09-14 13:21:50,81] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/sha256sum.cwl
[2018-09-14 13:21:50,87] [info] Pre-Processing /home/jeremiah/gdc-dnaseq-cwl/tools/integrity_to_sqlite.cwl
[2018-09-14 13:21:51,02] [info] Pre Processing Inputs...
[2018-09-14 13:21:51,27] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-6d01716",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2018-09-14 13:21:51,38] [info] Metadata summary refreshing every 2 seconds.
[2018-09-14 13:21:51,44] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-09-14 13:21:51,45] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-09-14 13:21:51,51] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2018-09-14 13:21:52,32] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2018-09-14 13:21:52,35] [info] SingleWorkflowRunnerActor: Version 35-fd560e9-SNAP
[2018-09-14 13:21:52,36] [info] SingleWorkflowRunnerActor: Submitting workflow
[2018-09-14 13:21:52,42] [info] CWL (Unspecified version) workflow 6f311835-f1fe-4bbd-8fbb-c5543373d039 submitted
[2018-09-14 13:21:52,43] [info] SingleWorkflowRunnerActor: Workflow submitted 6f311835-f1fe-4bbd-8fbb-c5543373d039
[2018-09-14 13:21:52,43] [info] 1 new workflows fetched
[2018-09-14 13:21:53,05] [info] WorkflowManagerActor Starting workflow 6f311835-f1fe-4bbd-8fbb-c5543373d039
[2018-09-14 13:21:53,06] [warn] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2018-09-14 13:21:53,09] [info] WorkflowManagerActor Successfully started WorkflowActor-6f311835-f1fe-4bbd-8fbb-c5543373d039
[2018-09-14 13:21:53,09] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2018-09-14 13:21:53,10] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2018-09-14 13:21:53,21] [info] MaterializeWorkflowDescriptorActor [6f311835]: Parsing workflow as CWL v1.0
[2018-09-14 13:21:55,91] [info] MaterializeWorkflowDescriptorActor [6f311835]: Call-to-Backend assignments: bam_ls_l -> Local, bam_readgroup_to_json -> Local, fastqc -> Local, json_to_sqlite -> Local, merge_readgroup_json_db -> Local, fastq_cleaner_se -> Local, picard_collecttargetedpcrmetrics_to_sqlite -> Local, biobambam_bamtofastq -> Local, readgroup_json_db -> Local, picard_collectmultiplemetrics -> Local, bai_integrity_to_db -> Local, gatk_calculatecontamination_to_sqlite -> Local, merge_exome_sqlite -> Local, picard_mergesamfiles -> Local, picard_collecthsmetrics -> Local, merge_sqlite -> Local, fastqc_basicstats_json -> Local, bam_integrity_to_db -> Local, merge_sqlite -> Local, bai_md5sum -> Local, merge_readgroup_json_db -> Local, merge_sqlite_bwa_se -> Local, samtools_index -> Local, picard_validatesamfile_bqsr -> Local, samtools_stats_to_sqlite -> Local, merge_amplicon_sqlite -> Local, bwa_se -> Local, picard_validatesamfile_bqsr_to_sqlite -> Local, fastqc_basicstats_json -> Local, fastqc1 -> Local, merge_readgroup_json_db -> Local, merge_all_sqlite -> Local, readgroup_json_db -> Local, bai_ls_l -> Local, bwa_pe -> Local, picard_collectmultiplemetrics_to_sqlite -> Local, bai_sha256 -> Local, picard_collectoxogmetrics -> Local, bam_sha256 -> Local, bam_readgroup_to_json -> Local, fastqc_db -> Local, fastqc_basicstats_json -> Local, gatk_applybqsr -> Local, merge_sqlite_fastq_clean_se -> Local, picard_markduplicates -> Local, fastq_cleaner_pe -> Local, fastqc2 -> Local, fastqc -> Local, picard_collectwgsmetrics -> Local, merge_sqlite_bwa_pe -> Local, picard_markduplicates_to_sqlite -> Local, fastqc_db -> Local, picard_collecttargetedpcrmetrics -> Local, readgroup_json_db -> Local, bam_readgroup_to_json -> Local, fastqc_db2 -> Local, empty_sqlite -> Local, gatk_calculatecontamination -> Local, fastqc_db1 -> Local, merge_sqlite -> Local, picard_collectoxogmetrics_to_sqlite -> Local, merge_readgroup_json_db -> Local, merge_sqlite -> Local, fastqc -> Local, json_to_sqlite -> Local, readgroup_json_db -> Local, gatk_baserecalibrator -> Local, merge_sqlite -> Local, bam_readgroup_to_json -> Local, picard_collectwgsmetrics_to_sqlite -> Local, bwa_se -> Local, samtools_idxstats -> Local, samtools_idxstats_to_sqlite -> Local, picard_collecthsmetrics_to_sqlite -> Local, merge_sqlite -> Local, fastqc_basicstats_json -> Local, fastqc_db -> Local, samtools_flagstat -> Local, bwa_se -> Local, bam_readgroup_to_json -> Local, samtools_flagstat_to_sqlite -> Local, gatk_getpileupsummaries -> Local, merge_sqlite_fastq_clean_pe -> Local, bam_reheader -> Local, samtools_stats -> Local, bam_md5sum -> Local
```

### PR DESCRIPTION
**Pull request by aednichols**
We were very close to having this work, but there was a comparison that was inadvertently returning false because it was comparing slightly different things.

Closes #4103

### CODE REVIEW

File: cwl/src/main/scala/cwl/model.scala [hunk 1]
```diff
@@ -190,15 +190,16 @@ case class SchemaDefRequirement(
...
+      inputEnumSchema.name.fold(false){name => FileAndId(name)(ParentName.empty).id equalsIgnoreCase FileAndId(tpe)(ParentName.empty).id}
     }
 
     types.toList.flatMap {
-    case Inl(inputRecordSchema: InputRecordSchema) if FileAndId(inputRecordSchema.name)(ParentName.empty).id equalsIgnoreCase FullyQualifiedName(tpe)(ParentName.empty).id=>
-          List(Coproduct[SchemaDefTypes](inputRecordSchema))
-    case Inr(Inl(inputEnumSchema: InputEnumSchema)) if matchesType(inputEnumSchema)=>
-      List(Coproduct[SchemaDefTypes](inputEnumSchema))
-    case _ => List()
+      case Inl(inputRecordSchema: InputRecordSchema) if FileAndId(inputRecordSchema.name)(ParentName.empty).id equalsIgnoreCase FileAndId(tpe)(ParentName.empty).id =>
```
Comment (cjllanwarne) [inline cwl/src/main/scala/cwl/model.scala]: [TOL] Not your fault but.....

I personally hate these `case Inl(...(Inl(Inr(value)...)` patterns because they're atrociously brittle to re-ordering of the coproduct definition. Much better IMO is the `select[InputRecordSchema]` method.

To use that method in a pattern match you'd need to define a custom unapply on the `SchemaDefTypes` coproduct with a case for each of its possible values.

Comment (aednichols) [reply cwl/src/main/scala/cwl/model.scala]: I wonder whether this is what makes IntelliJ hate this file so much [1]

[1] https://youtrack.jetbrains.com/issue/SCL-15243

**Comment by aednichols** [comment]
I noticed that the issue actually did inspire a conformance test, so I'm going to check out whether we can get credit for it now

https://github.com/common-workflow-language/common-workflow-language/pull/787

File: src/ci/resources/papi_v2_conformance_expected_failures.txt [hunk 2]
```diff
@@ -3,3 +3,32 @@
...
+166
+170
+171
+172
+173
+174
+175
+190
+191
+196
```
Comment (salonishah11) [inline src/ci/resources/papi_v2_conformance_expected_failures.txt]: Out of interest, what is causing all these tests to fail? Are these new tests?

Comment (aednichols) [reply src/ci/resources/papi_v2_conformance_expected_failures.txt]: Yep.

Our previous CWL pin is from August 2018 and this is the first time Cromwell has ever seen tests 133-197

https://github.com/common-workflow-language/common-workflow-language/blame/master/v1.0/conformance_test_v1.0.yaml#L1875

**Comment by aednichols** [comment]
Disappointingly, conformance test #135, the packed CWL one, is failing

File: src/ci/resources/papi_v2_conformance_expected_failures.txt (hunk 2 above)
Comment (salonishah11) [reply src/ci/resources/papi_v2_conformance_expected_failures.txt]: Ah I see. Thank you! :)

**Comment by aednichols** [comment]
I submitted a CWL PR to fix one of two issues that kept the conformance from passing: https://github.com/common-workflow-language/common-workflow-language/pull/849

I intend to merge this PR as-is and follow up on the conformance stuff.

It seems my comment at standup regarding a re-thumb from @cjllanwarne was misplaced as the PR is still awaiting an original thumb
