### PR TITLE
Copy workflow logs even upon failure closes #1621

### LINKED ISSUE #1621: Always copy per-workflow logs
Right now per-workflow logs are not (ever?) copied when the workflow fails.  We need these logs to help debug issues in execution, so they are most helpful when the workflow fails.

### PR DESCRIPTION
**Pull request by ruchim**

### CODE REVIEW

File: engine/src/main/scala/cromwell/engine/workflow/lifecycle/CopyWorkflowLogsActor.scala [hunk 1]
```diff
@@ -25,6 +25,7 @@ object CopyWorkflowLogsActor {
 
 // This could potentially be turned into a more generic "Copy/Move something from A to B"
 // Which could be used for other copying work (outputs, call logs..)
+// Which could be used for other copying work (outputs, call logs..)
```
Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/workflow/lifecycle/CopyWorkflowLogsActor.scala]: double double comment comment

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 2]
```diff
@@ -298,16 +297,31 @@ class WorkflowActor(val workflowId: WorkflowId,
...
+
+        val workflowOptions = stateData.workflowDescriptor match {
+          case Some(wfDescriptor) => wfDescriptor.backendDescriptor.workflowOptions
+          case _ => bruteForceWorkflowOptions
+        }
+
+        val pathBuilders: List[PathBuilder] = stateData.workflowDescriptor match {
+          case Some(wfDescriptor) => wfDescriptor.pathBuilders
+          case _ => bruteForcePathBuilders(workflowOptions)
+        }
```
Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: could do these in one pattern match

```scala

lazy val bruteForceWorkflowOptions = ... // same as it is currently
lazy val bruteForcePathBuilders = ... // closes over bruteForceWorkflowOptions

val (workflowOptions, pathBuilders) = stateData.workflowDescriptor match {
  case Some(wd) => (wd.backendDescriptor.workflowOptions, wd.pathBuilders)
  case None => (bruteForceWorkflowOptions, bruteForcePathBuilders)
}
```

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 3]
```diff
@@ -298,16 +297,31 @@ class WorkflowActor(val workflowId: WorkflowId,
...
       // Copy/Delete workflow logs
       if (WorkflowLogger.isEnabled) {
-        stateData.workflowDescriptor foreach { wd =>
-          wd.getWorkflowOption(FinalWorkflowLogDir) match {
+        /*
+          * The submitted workflow options have been previously validated by the CromwellApiHandler. These are
+          * being recreated so that in case MaterializeWorkflowDescriptor fails, the workflow logs can still
+          * be copied by accessing the workflow options outside of the EngineWorkflowDescriptor.
+          */
+        def bruteForceWorkflowOptions = WorkflowOptions.fromJsonString(workflowSources.workflowOptionsJson).get
```
Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: ok to throw here if we're on the unhappy side of the `Try`?

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 4]
```diff
@@ -142,10 +151,20 @@ class WorkflowActorSpec extends CromwellTestKitSpec with WorkflowDescriptorBuild
...
+      copyWorkflowLogsPrope watch dummyLogCopyRouter
       actor ! AbortWorkflowCommand
       finalizationProbe.expectNoMsg(AwaitAlmostNothing)
       deathwatch.expectTerminated(actor)
     }
+
+    "copy workflow logs in the event of MaterializeWorkflowDescriptorFailureResponse" in {
+      val actor = createWorkflowActor(MaterializingWorkflowDescriptorState)
+      deathwatch watch actor
+      actor ! MaterializeWorkflowDescriptorFailureResponse(new Exception("Workflow Materialization Failed"))
```
Comment (mcovarr) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: It might be nice to have the exception message make clear that the failure is intentional, e.g. "Intentionally failing workflow materialization to test log copying" or something like that

**Comment by mcovarr** [comment]
:+1:

File: engine/src/main/scala/cromwell/engine/workflow/lifecycle/CopyWorkflowLogsActor.scala (hunk 1 above)
Comment (ruchim) [inline engine/src/main/scala/cromwell/engine/workflow/lifecycle/CopyWorkflowLogsActor.scala]: you miss nothing

Comment (geoffjentry) [inline engine/src/main/scala/cromwell/engine/workflow/lifecycle/CopyWorkflowLogsActor.scala]: Except the start of standup

Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/workflow/lifecycle/CopyWorkflowLogsActor.scala]: 🔥

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala (hunk 4 above)
Comment (cjllanwarne) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: I always appreciate a big friendly "DON'T WORRY THIS EXCEPTION WAS INTENDED FOR THE TESTS"

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 5]
```diff
@@ -28,14 +31,20 @@ class WorkflowActorSpec extends CromwellTestKitSpec with WorkflowDescriptorBuild
...
   var currentWorkflowId: WorkflowId = _
   val currentLifecycleActor = TestProbe()
-  val wdlSources = ThreeStep.asWorkflowSources()
+  val wdlSources = ThreeStep.asWorkflowSources(workflowOptions = mockWorkflowOptions)
   val descriptor = createMaterializedEngineWorkflowDescriptor(WorkflowId.randomId(), workflowSources = wdlSources)
   val supervisorProbe = TestProbe()
   val deathwatch = TestProbe()
   val finalizationProbe = TestProbe()
-
+  val copyWorkflowLogsPrope = TestProbe()
```
Comment (cjllanwarne) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: Typo in `prope`

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 6]
```diff
@@ -142,10 +151,20 @@ class WorkflowActorSpec extends CromwellTestKitSpec with WorkflowDescriptorBuild
     "not run Finalization actor if aborted when in MaterializingWorkflowDescriptorState" in {
       val actor = createWorkflowActor(MaterializingWorkflowDescriptorState)
       deathwatch watch actor
+      copyWorkflowLogsPrope watch dummyLogCopyRouter
```
Comment (cjllanwarne) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: This doesn't appear to be doing anything

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 7]
```diff
@@ -142,10 +151,20 @@ class WorkflowActorSpec extends CromwellTestKitSpec with WorkflowDescriptorBuild
...
       deathwatch.expectTerminated(actor)
     }
+
+    "copy workflow logs in the event of MaterializeWorkflowDescriptorFailureResponse" in {
+      val actor = createWorkflowActor(MaterializingWorkflowDescriptorState)
+      deathwatch watch actor
+      actor ! MaterializeWorkflowDescriptorFailureResponse(new Exception("Workflow Materialization Failed"))
+      finalizationProbe.expectNoMsg(AwaitAlmostNothing)
+      copyWorkflowLogsPrope.expectMsg(CopyWorkflowLogsActor.Copy(currentWorkflowId, mockDir))
+      deathwatch.expectTerminated(actor)
```
Comment (cjllanwarne) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: ToL: Is it intended that the workflow will "complete" before the copy completes?

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala (hunk 3 above)
Comment (cjllanwarne) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: Probably better to `.getOrElse("{}")`

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala [hunk 8]
```diff
@@ -28,14 +31,20 @@ class WorkflowActorSpec extends CromwellTestKitSpec with WorkflowDescriptorBuild
     }
   })
 
+  val mockDir = Paths.get("/where/to/copy/wf/logs")
+  val mockWorkflowOptions =
+    s"""
+       |{ "final_workflow_log_dir" : "$mockDir" }
+     """.stripMargin
```
Comment (kshakir) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]:
```scala
val mockWorkflowOptions = s"""{ "final_workflow_log_dir" : "$mockDir" }"""
```

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala [hunk 9]
```diff
@@ -332,6 +346,7 @@ class WorkflowActor(val workflowId: WorkflowId,
                                failures: Option[List[Throwable]]) = {
     val finalizationActor = makeFinalizationActor(workflowDescriptor, jobExecutionMap, workflowOutputs)
     finalizationActor ! StartFinalizationCommand
-    goto(FinalizingWorkflowState) using data.copy(lastStateReached = StateCheckpoint(stateName, failures))
+    goto (FinalizingWorkflowState) using data.copy(lastStateReached = StateCheckpoint (stateName, failures))
```
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala]: Why the ex tra spa ces?

**Comment by kshakir** [comment]
Looks good. 👍  once comments addressed.

File: engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala (hunk 7 above)
Comment (ruchim) [inline engine/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala]: It's intended that it shoots off the request before the WorkflowActor transitions to a FailedState...does that answer your question or are we talking about different things?
