### PR TITLE
Failure metadata migration. Closes #2037. Closes #2039

### LINKED ISSUE #2037: Inconsistent failure messages for workflows
We are trying to expose workflow failure messages to the user in Firecloud. However, the failures field seems to have an inconsistent format:

Compare the failures sections for the following:

```
{
  "workflowName": "echo_strings",
  "submittedFiles": {
    "inputs": "{...},
  "calls": {
    "echo_strings.echo_files": [{
      "preemptible": false,
      "retryableFailure": false,
      "executionStatus": "Failed",
      "stdout": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/b6b190d6-8640-4638-94cd-15f16b194f38/echo_strings/c386672d-0248-4968-9b1a-114f5f5c4706/call-echo_files/echo_files-stdout.log",
      "backendStatus": "Failed",
      "shardIndex": -1,
      "jes": {
        "endpointUrl": "https://genomics.googleapis.com/",
        "machineType": "us-central1-c/n1-standard-1",
        "googleProject": "broad-dsde-dev",
        "executionBucket": "gs://cromwell-dev/cromwell-executions",
        "zone": "us-central1-c",
        "instanceName": "ggp-3462354720519617596"
      },
      "runtimeAttributes": {...},
      "cache": {
        "allowResultReuse": true
      },
      "Effective call caching mode": "CallCachingOff",
      "inputs": {...
      },
      "failures": [{
        "message": "Task c386672d-0248-4968-9b1a-114f5f5c4706:echo_files failed: error code 5. Message: 8: Failed to pull image ubuntu:latest: \"docker --config /tmp/.docker/ pull ubuntu:latest\" failed: exit status 1: Pulling repository docker.io/library/ubuntu\nNetwork timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.\n"
      }],
      "jobId": "operations/EJiq_oWfKxi8-N-X4qiwhjAgw7vetLsXKg9wcm9kdWN0aW9uUXVldWU",
      "backend": "JES",
      "end": "2017-01-30T19:14:19.708Z",
      "stderr": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/b6b190d6-8640-4638-94cd-15f16b194f38/echo_strings/c386672d-0248-4968-9b1a-114f5f5c4706/call-echo_files/echo_files-stderr.log",
      "callRoot": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/b6b190d6-8640-4638-94cd-15f16b194f38/echo_strings/c386672d-0248-4968-9b1a-114f5f5c4706/call-echo_files",
      "attempt": 1,
      "executionEvents": [...],
      "backendLogs": {
        "log": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/b6b190d6-8640-4638-94cd-15f16b194f38/echo_strings/c386672d-0248-4968-9b1a-114f5f5c4706/call-echo_files/echo_files.log"
      },
      "start": "2017-01-30T19:00:03.896Z"
    }]
  },
  "outputs": {

  },
  "workflowRoot": "/b6b190d6-8640-4638-94cd-15f16b194f38/echo_strings/c386672d-0248-4968-9b1a-114f5f5c4706/",
  "id": "c386672d-0248-4968-9b1a-114f5f5c4706",
  "inputs": {...
  },
  "submission": "2017-01-30T19:00:00.796Z",
  "status": "Failed",
  "failures": [{
    "message": "Task c386672d-0248-4968-9b1a-114f5f5c4706:echo_files failed: error code 5. Message: 8: Failed to pull image ubuntu:latest: \"docker --config /tmp/.docker/ pull ubuntu:latest\" failed: exit status 1: Pulling repository docker.io/library/ubuntu\nNetwork timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.\n"
  }],
  "workflowLog": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/b6b190d6-8640-4638-94cd-15f16b194f38/workflow.logs/workflow.c386672d-0248-4968-9b1a-114f5f5c4706.log",
  "end": "2017-01-30T19:14:20.002Z",
  "start": "2017-01-30T19:00:03.040Z"
}

```
Here it's an array of "message"s
```
{
  "workflowName": "aggregate_data_workflow",
  "submittedFiles": {... },
  "calls": {
    "aggregate_data_workflow.aggregate_data": [{
      "retryableFailure": false,
      "executionStatus": "Failed",
      "stdout": "/cromwell-executions/aggregate_data_workflow/3608d6ca-fbb4-4232-b197-268058470bfc/call-aggregate_data/execution/stdout",
      "shardIndex": -1,
      "runtimeAttributes": {
        "docker": "broadgdac/aggregate_data:31",
        "failOnStderr": false,
        "continueOnReturnCode": "0"
      },
      "cache": {
        "allowResultReuse": true
      },
      "Effective call caching mode": "CallCachingOff",
      "inputs": {...
      },
      "returnCode": -1,
      "failures": [{
        "message": "Call aggregate_data_workflow.aggregate_data: return code was -1"
      }, {
        "message": "Call aggregate_data_workflow.aggregate_data: return code was -1"
      }, {
        "message": "Call aggregate_data_workflow.aggregate_data: return code was -1"
      }],
      "jobId": "2957",
      "backend": "JES",
      "end": "2016-12-02T15:05:42.655Z",
      "stderr": "/cromwell-executions/aggregate_data_workflow/3608d6ca-fbb4-4232-b197-268058470bfc/call-aggregate_data/execution/stderr",
      "callRoot": "/cromwell-executions/aggregate_data_workflow/3608d6ca-fbb4-4232-b197-268058470bfc/call-aggregate_data",
      "attempt": 1,
      "executionEvents": [...]
  },
  "outputs": {

  },
  "workflowRoot": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/9ea737cd-a512-4c62-820c-dd1505ea7676/aggregate_data_workflow/3608d6ca-fbb4-4232-b197-268058470bfc",
  "id": "3608d6ca-fbb4-4232-b197-268058470bfc",
  "inputs": {...
  },
  "submission": "2016-12-01T21:21:40.188Z",
  "status": "Failed",
  "failures": [{
    "message": "Call aggregate_data_workflow.aggregate_data: return code was -1"
  }, {
    "message": "Call aggregate_data_workflow.aggregate_data: return code was -1"
  }, {
    "message": "Call aggregate_data_workflow.aggregate_data: return code was -1"
  }],
  "workflowLog": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/9ea737cd-a512-4c62-820c-dd1505ea7676/workflow.logs/workflow.3608d6ca-fbb4-4232-b197-268058470bfc.log",
  "end": "2016-12-02T15:05:42.868Z",
  "start": "2016-12-02T15:05:40.873Z"
}
```

Here there's no "message" and there are "timestamp" and "failure"

```
{
  "workflowName": "aggregate_data_workflow",
  "submittedFiles": {
    "options": "{\n  \"default_runtime_attributes\": {\n    \"zones\": \"us-central1-b\"\n  },\n  \"google_project\": \"broad-dsde-dev\",\n  \"auth_bucket\": \"gs://cromwell-auth-broad-dsde-dev\",\n  \"refresh_token\": \"cleared\",\n  \"account_name\": \"abaumann.firecloud@gmail.com\",\n  \"jes_gcs_root\": \"gs://fc-5539c024-3ba8-4ed1-97c3-82fed2675776/1626e6be-60ed-48b1-9bbc-a3fdef4a90f5\"\n}",
    "inputs": "{\"aggregate_data_workflow.aggregate_data.input_array\":[\"bar, baz\"]}",
    "workflow": "task aggregate_data {\n\tArray[File] input_array\n\n\tcommand {\n    echo \"foo\"\n\n\t}\n\n\toutput {\n\t\tArray[Array[File]] output_array = [input_array]\n\t}\n\n\truntime {\n\t\tdocker : \"broadgdac/aggregate_data:31\"\n\t}\n\n\tmeta {\n\t\tauthor : \"Tim DeFreitas\"\n\t\temail : \"timdef@broadinstitute.org\"\n\t}\n\n}\n\nworkflow aggregate_data_workflow {\n\tcall aggregate_data\n}"
  },
  "calls": {
    "aggregate_data_workflow.aggregate_data": [{
      "preemptible": false,
      "executionStatus": "Failed",
      "stdout": "gs://fc-5539c024-3ba8-4ed1-97c3-82fed2675776/1626e6be-60ed-48b1-9bbc-a3fdef4a90f5/aggregate_data_workflow/7be16669-0f81-4e19-96a0-dbe4b72cee8e/call-aggregate_data/aggregate_data-stdout.log",
      "shardIndex": -1,
      "outputs": {

      },
      "runtimeAttributes": {
        "preemptible": "0",
        "failOnStderr": "false",
        "bootDiskSizeGb": "10",
        "disks": "local-disk 10 SSD",
        "continueOnReturnCode": "0",
        "docker": "broadgdac/aggregate_data:31",
        "cpu": "1",
        "zones": "us-central1-b",
        "memory": "2GB"
      },
      "cache": {
        "allowResultReuse": true
      },
      "inputs": {
        "input_array": ["bar, baz"]
      },
      "failures": [{
        "timestamp": "2016-08-01T19:58:04.704000Z",
        "failure": "com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"message\" : \"Pipeline 9453747469251135900: Unable to evaluate parameters: %!(EXTRA string=parameter \\\"input_array-0\\\" has invalid value: bar, baz)\",\n    \"reason\" : \"badRequest\"\n  } ],\n  \"message\" : \"Pipeline 9453747469251135900: Unable to evaluate parameters: %!(EXTRA string=parameter \\\"input_array-0\\\" has invalid value: bar, baz)\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}"
      }],
      "backend": "JES",
      "end": "2016-08-01T19:58:05.000000Z",
      "stderr": "gs://fc-5539c024-3ba8-4ed1-97c3-82fed2675776/1626e6be-60ed-48b1-9bbc-a3fdef4a90f5/aggregate_data_workflow/7be16669-0f81-4e19-96a0-dbe4b72cee8e/call-aggregate_data/aggregate_data-stderr.log",
      "attempt": 1,
      "executionEvents": [],
      "backendLogs": {
        "log": "gs://fc-5539c024-3ba8-4ed1-97c3-82fed2675776/1626e6be-60ed-48b1-9bbc-a3fdef4a90f5/aggregate_data_workflow/7be16669-0f81-4e19-96a0-dbe4b72cee8e/call-aggregate_data/aggregate_data.log"
      },
      "start": "2016-08-01T19:56:48.000000Z"
    }]
  },
  "outputs": {

  },
  "id": "7be16669-0f81-4e19-96a0-dbe4b72cee8e",
  "submission": "2016-08-01T19:56:48.000000Z",
  "status": "Failed",
  "end": "2016-08-01T19:58:05.000000Z",
  "start": "2016-08-01T19:56:48.000000Z"
}
```

Here the failures section has a nested structure.
```
{
  "workflowName": "echo_strings",
  "submittedFiles": {
    "inputs": "..."
  },
  "calls": {

  },
  "outputs": {

  },
  "id": "12677a12-bca2-41a6-b583-596262c7e0c7",
  "inputs": {...
  },
  "submission": "2017-01-31T17:54:48.812Z",
  "status": "Failed",
  "failures": [{
    "causedBy": {
      "causedBy": {
        "message": "connect timed out"
      },
      "message": "Error getting access token for service account: "
    },
    "message": "Failed to upload authentication file"
  }],
  "workflowLog": "gs://fc-2d3fd356-e3be-4953-92f1-60af623e6fa5/4503a3b1-5b50-4474-8a31-809e73510622/workflow.logs/workflow.12677a12-bca2-41a6-b583-596262c7e0c7.log",
  "end": "2017-01-31T17:55:10.439Z",
  "start": "2017-01-31T17:54:50.257Z"
}
```

This inconsistency in the format of the failure messages makes it difficult to show properly formated failure messages in our UI.

### LINKED ISSUE #2039: Migrate Unflat Failure Metadata
Migrate existing failures in the metadata database from the former un-flat failure metadata style:
```
"failures": [{
    "causedBy": {
      "causedBy": {
        "message": "connect timed out"
      },
      "message": "Error getting access token for service account: "
    },
    "message": "Failed to upload authentication file"
  }]
```

to the new flat style that new workflow metadata will be created with:
```
  "failures": [{
    "message": "connect timed out"
  }, {
    "message": "Failed to upload authentication file"
  }, {
    "message": "Error getting access token for service account: "
  }]
```

Also note that aggregated exceptions were previously being input using the same random integer for every message part (i.e. every part of the aggregate was overwriting the previous one), so migration could... fix that.

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

File: database/migration/src/main/resources/changesets/failure_metadata_scripts/guarantee_causedBy.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+SELECT WORKFLOW_EXECUTION_UUID, REPLACE(METADATA_KEY, "message", "causedBy[]"), CALL_FQN, JOB_SCATTER_INDEX, JOB_RETRY_ATTEMPT, METADATA_TIMESTAMP
+FROM METADATA_ENTRY AS t1
+WHERE METADATA_KEY LIKE '%failures[%]%message'
+AND NOT EXISTS (SELECT *
+             	FROM METADATA_ENTRY AS t2
+             	WHERE t2.WORKFLOW_EXECUTION_UUID = t1.WORKFLOW_EXECUTION_UUID
+             	  AND (t2.CALL_FQN = t1.CALL_FQN OR (t2.CALL_FQN IS NULL AND t1.CALL_FQN IS NULL))
+             	  AND (t2.JOB_SCATTER_INDEX = t1.JOB_SCATTER_INDEX OR (t2.JOB_SCATTER_INDEX IS NULL AND t1.JOB_SCATTER_INDEX IS NULL))
+             	  AND (t2.JOB_RETRY_ATTEMPT = t1.JOB_RETRY_ATTEMPT OR (t2.JOB_RETRY_ATTEMPT IS NULL AND t1.JOB_RETRY_ATTEMPT IS NULL))
+                  AND t2.METADATA_KEY LIKE REPLACE(t1.METADATA_KEY, "message", "causedBy%")
```
Comment (kshakir) [inline database/migration/src/main/resources/changesets/failure_metadata_scripts/guarantee_causedBy.sql]: ToL: Similar preference for `CONCAT` instead of `REPLACE`, and `:` prefixing for keys.

File: database/migration/src/main/scala/cromwell/database/migration/failuremetadata/DeduplicateFailureMessageIds.scala [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+  val primaryKeyColumn = "METADATA_JOURNAL_ID"
+  val workflowIdColumn = "WORKFLOW_EXECUTION_UUID"
+  val metadataKeyColumn = "METADATA_KEY"
+  val callFqnColumn = "CALL_FQN"
+  val jobScatterIndexColumn = "JOB_SCATTER_INDEX"
+  val retryAttemptColumn = "JOB_RETRY_ATTEMPT"
+  val contentEqualityCheck = List(workflowIdColumn, metadataKeyColumn, callFqnColumn, jobScatterIndexColumn, retryAttemptColumn)
+    .map(s => s"(t2.$s = t1.$s OR (t2.$s IS NULL AND t1.$s IS NULL))").mkString(" AND ")
+
+  val fixableFailureMessageFilter = "METADATA_KEY LIKE '%failures[%]%message'"
```
Comment (kshakir) [inline database/migration/src/main/scala/cromwell/database/migration/failuremetadata/DeduplicateFailureMessageIds.scala]: `LIKE 'failures[%]%:message'`

File: database/migration/src/main/resources/changesets/failure_metadata.xml [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd">
+
+    <changeSet author="cjllanwarne" id="failure_to_message" dbms="mysql">
+        <sqlFile relativeToChangelogFile="true" path="failure_metadata_scripts/failure_to_message.sql" />
+    </changeSet>
+
+    <changeSet author="cjllanwarne" id="remove_failure_timestamp" dbms="mysql">
+        <delete tableName="METADATA_ENTRY">
+            <where>METADATA_KEY LIKE '%failures%:timestamp'</where>
```
Comment (kshakir) [inline database/migration/src/main/resources/changesets/failure_metadata.xml]: How about `LIKE 'failures[%]:timestamp'`?

**Comment by kshakir** [comment]
👍  with comments above

**Comment by kshakir** [comment]
I refuse to believe that `\n` can't be removed, but w/e 😉 . 👍  once Travis is happy.

**Comment by Horneth** [comment]
👍
