### PR TITLE
[develop] Job execution token dispenser actor fixes

### LINKED ISSUE #4908: JobExecutionTokenDispenserActor crashes not infrequently
The singleton `JobExecutionTokenDispenserActor` seems to crash quite a bit with no cause currently known. The default Akka supervision strategy causes JETD to be restarted, but the reincarnated JETD knows nothing of its predecessors' token allocations. This will cause tokens to be dispensed as if none are outstanding and returned tokens to produce error messages like:

```
2019-04-26 19:40:20 [cromwell-system-akka.actor.default-dispatcher-1109] ERROR c.e.w.t.JobExecutionTokenDispenserActor - Job execution token returned from incorrect actor: 202ffd24-a696-4edc-b832-a75f1127fdb4-EngineJobExecutionActor-Gatk3BamToGVCF.PrintReads:1:1
```

JETD restarts in production can be found by looking for `"log token queue events"` in Kibana where there is no corresponding Cromwell restart.

### PR DESCRIPTION
**Pull request by cjllanwarne**
Closes #4908.

Combines the changes in #4909 (sanity check in case this happens again) and #4923 (should prevent it happening in the first place) and adds a test case for one scenario which was found to cause this problem

### CODE REVIEW

File: engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala [hunk 1]
```diff
@@ -47,7 +48,14 @@ final case class TokenQueue(queues: Map[String, Queue[TokenQueuePlaceholder]],
...
+    val guaranteedNonEmptyQueues = queues.filterNot { case (hogGroup, q: Queue[_]) =>
+      val empty = q.isEmpty
+      if (empty) logger.warn(s"Programmer error: Empty token queue value still present in TokenQueue: $hogGroup")
+      empty
+    }
+    recursingDequeue(guaranteedNonEmptyQueues, Vector.empty, queueOrder)
+  }
 
   private def recursingDequeue(queues: Map[String, Queue[TokenQueuePlaceholder]], queuesTried: Vector[String], queuesRemaining: Vector[String]): DequeueResult = {
     if (queuesRemaining.isEmpty) {
```
Comment (aednichols) [inline engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala]: [ToL] I wonder if we could put this empty check in `dequeue` and skip calling `recursingDequeue` at all

Just a way of putting two related checks - list not empty & no empty items in list - in the same place

Comment (cjllanwarne) [reply engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala]: I think it could be in `dequeue` as well - but this looks like it serves as the base case escape for the recursion function so I think it's still needed here as well

File: engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala [hunk 2]
```diff
@@ -17,7 +18,7 @@ import scala.collection.immutable.Queue
 final case class TokenQueue(queues: Map[String, Queue[TokenQueuePlaceholder]],
                             queueOrder: Vector[String],
                             eventLogger: TokenEventLogger,
-                            private [tokens] val pool: UnhoggableTokenPool) {
+                            private [tokens] val pool: UnhoggableTokenPool) extends LazyLogging {
```
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala]:
```suggestion
                            private [tokens] val pool: UnhoggableTokenPool) extends StrictLogging {
```

File: engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala [hunk 3]
```diff
@@ -57,32 +65,48 @@ final case class TokenQueue(queues: Map[String, Queue[TokenQueuePlaceholder]],
...
+      } else {
+        leaseTry match {
+          case thl: TokenHoggingLease =>
+            val (placeholder, newQueue) = oldQueue.dequeue
+            val (newQueues, newQueueOrder) = if (newQueue.isEmpty) {
+              (queues - hogGroup, remainingHogGroups ++ queuesTried)
+            } else {
+              (queues + (hogGroup -> newQueue), remainingHogGroups ++ queuesTried :+ hogGroup)
+            }
+            DequeueResult(Some(LeasedActor(placeholder, thl)), TokenQueue(newQueues, newQueueOrder, eventLogger, pool))
```
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala]:
```suggestion
            DequeueResult(Option(LeasedActor(placeholder, thl)), TokenQueue(newQueues, newQueueOrder, eventLogger, pool))
```

File: engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala [hunk 4]
```diff
@@ -82,24 +82,16 @@ class JobExecutionTokenDispenserActor(override val serviceRegistryActor: ActorRe
...
-  private def createNewQueue(tokenType: JobExecutionTokenType): TokenQueue = {
-    val newQueue = TokenQueue(tokenType, tokenEventLogger)
-    tokenQueues += tokenType -> newQueue
-    newQueue
-  }
-
   private def distribute(n: Int) = if (tokenQueues.nonEmpty) {
 
+    // Turning a mutable `Map` to a `List` and using an indexed pointer?
     val iterator = new RoundRobinQueueIterator(tokenQueues.values.toList, currentTokenQueuePointer)
```
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala]: Before merging, can we get an answer to this question and update the comment?

File: engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala [hunk 5]
```diff
@@ -126,6 +118,7 @@ class JobExecutionTokenDispenserActor(override val serviceRegistryActor: ActorRe
       case LeasedActor(queuePlaceholder, lease) =>
         log.error(s"Actor ${queuePlaceholder.actor.path} requested a job execution token more than once. This situation should have been impossible.")
         queuePlaceholder.actor ! JobExecutionTokenDispensed
+        // If there are going to be > 1 actors mapping to this lease why is the lease being released?
         lease.release()
```
Comment (kshakir) [inline engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala]: Before merging, can we also get an answer to this question and update the comment?

File: engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala (hunk 3 above)
Comment (cjllanwarne) [reply engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala]: OK but I still think this is strictly worse than using `Some` in these situations

**Comment by cjllanwarne** [comment]
@kshakir @mcovarr I think I answered your commented questions with new comments. Let me know if they need more explanation/detail
