### PR TITLE
Better JES globbing. Closes #1395. Closes #838. Probably closes #1391. Probably closes #1248. 

### LINKED ISSUE #838: Nested scatter blocks
It would be great if Cromwell supported nested scatter blocks. For example:

```
workflow wf {

  Array[Array[String]] array

  scatter (arr in array) {
    scatter (i in arr) {
      call foo {
        input: str=i
      }
    }
  }
}
```

### LINKED ISSUE #1248: Post-Processing slows down to a crawl and fails with large globs
@jsotobroad -- take it away

### LINKED ISSUE #1395: JES Globbing should use new glob count to beat eventual consistency
Currently, to process a glob on JES, Cromwell does an `ls` of the google cloud storage location.  The problem with this is that ls is eventually consistent, which leads to bugs like #843 

JES has added a feature (#28858407) where they now return the number of files that matched the glob as part of their metadata.  These appear as events of the form

`{Description: "copied 3 file(s) to \"gs://my-bucket/out/\"",
           StartTime:   {Seconds: 1470063955,
                         Nanos:   748725437}},`

In Cromwell, when processing these globs, we should poll (with adjustable maximum timeout) for this number of files to appear via the ls.  If they do not appear after the timeout, the task should fail with an appropriate error message.

If we are processing globs on GCS and NOT using JES, the best we can do is just grab and go via the ls (as we are doing currently for JES).

### PR DESCRIPTION
**Pull request by cjllanwarne**
JES globbing now:
- Takes a few hundred milliseconds to resolve globs, rather than several minutes
- Doesn't suffer from eventual consistency

User-facing changes:
- Uses bash-style glob syntax instead of python style glob syntax

### CODE REVIEW

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 1]
```diff
@@ -126,7 +126,7 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
 
   override def receive: Receive = pollingActorClientReceive orElse jesReceiveBehavior orElse super.receive
 
-  private def globOutputPath(glob: String) = callRootPath.resolve(s"glob-${glob.md5Sum}/")
+//  private def globOutputPath(glob: String) = callRootPath.resolve(s"glob-${glob.md5Sum}/")
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Delete this line

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 2]
```diff
@@ -212,26 +211,59 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
...
+  private[jes] def findGlobOutputs(jobDescriptor: BackendJobDescriptor): Seq[WdlGlobFile] = {
+    (call.task.findOutputFiles(jobDescriptor.fullyQualifiedInputs, NoFunctions) map relativeLocalizationPath).distinct collect {
+      case glob: WdlGlobFile => glob
+    }
+  }
+
   private[jes] def generateJesOutputs(jobDescriptor: BackendJobDescriptor): Seq[JesFileOutput] = {
     val wdlFileOutputs = call.task.findOutputFiles(jobDescriptor.fullyQualifiedInputs, NoFunctions) map relativeLocalizationPath
 
     // Create the mappings. GLOB mappings require special treatment (i.e. stick everything matching the glob in a folder)
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Remove this comment

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 3]
```diff
@@ -212,26 +211,59 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
...
+    val result = wdlFileOutputs.distinct flatMap { wdlFile =>
+      wdlFile match {
+        case singleFile: WdlSingleFile => generateJesSingleFileOutputs(singleFile)
+        case globFile: WdlGlobFile => generateJesGlobFileOutputs(globFile)
       }
-      val (relpath, disk) = relativePathAndAttachedDisk(wdlFile.value, runtimeAttributes.disks)
-      JesFileOutput(makeSafeJesReferenceName(wdlFile.value), destination, relpath, disk)
     }
+
+    log.info("Output mappings:\n" + result.mkString("\n"))
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Remove this debug line

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 4]
```diff
@@ -212,26 +211,59 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
...
+    val destination = callRootPath.resolve(wdlFile.value.stripPrefix("/")).toUri.toString
+    val (relpath, disk) = relativePathAndAttachedDisk(wdlFile.value, runtimeAttributes.disks)
+    List(JesFileOutput(makeSafeJesReferenceName(wdlFile.value), destination, relpath, disk))
+  }
+
+  private def generateJesGlobFileOutputs(wdlFile: WdlGlobFile): List[JesFileOutput] = {
+    val globDirectory = callEngineFunctions.globDirectory(wdlFile.value)            // E.g. "glob-7bb0c33ac658a900e2c3804726fc1d2a/"
+    val globListFile = globDirectory.stripSuffix("/") + ".list"                     // E.g. "glob-7bb0c33ac658a900e2c3804726fc1d2a.list"
+    val gcsGlobDirectoryDestinationPath = callRootPath.resolve(globDirectory).toUri.toString      // E.g. "gs://.../.../.../glob-7bb0c33ac658a900e2c3804726fc1d2a/"
+    val gcsGlobListFileDestinationPath = callRootPath.resolve(globListFile).toUri.toString   // E.g. "gs://.../.../.../glob-7bb0c33ac658a900e2c3804726fc1d2a.list"
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Remove the notes-to-self comments

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 5]
```diff
@@ -250,10 +295,13 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
          |(
          |cd ${JesWorkingDisk.MountPoint}
          |$command
+         |$globManipulations
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Might be better in a separate block, eg:
```
(
cd ${JesWorkingDisk.MountPoint}
$command
)
(
cd ${JesWorkingDisk.MountPoint}
$globManipulations
)
```

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 6]
```diff
@@ -250,10 +295,13 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
...
          |)
          |echo $$? > $rcPath
        """.stripMargin.trim
 
+    log.info("Generated script file:\n{}", fileContent)
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Remove

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesParameters.scala [hunk 7]
```diff
@@ -35,4 +35,6 @@ final case class JesFileOutput(name: String, gcs: String, local: Path, mount: Je
     )
   }
   val toGoogleRunParameter: String = gcs
+
+  override def toString = s"[$name]: ($local) -> $gcs"
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesParameters.scala]: Revert

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 8]
```diff
@@ -212,26 +209,52 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
...
   }
 
+  private def generateJesSingleFileOutputs(wdlFile: WdlSingleFile): JesFileOutput = {
+    val destination = callRootPath.resolve(wdlFile.value.stripPrefix("/")).toUri.toString
+    val (relpath, disk) = relativePathAndAttachedDisk(wdlFile.value, runtimeAttributes.disks)
+    JesFileOutput(makeSafeJesReferenceName(wdlFile.value), destination, relpath, disk)
+  }
+
+  private def generateJesGlobFileOutputs(wdlFile: WdlGlobFile): List[JesFileOutput] = {
+    val globDirectory = callEngineFunctions.globName(wdlFile.value) + "/"
```
Comment (mcovarr) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: pull `callEngineFunctions.globName(wdlFile.value)` to a variable?

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 9]
```diff
@@ -212,26 +209,52 @@ class JesAsyncBackendJobExecutionActor(override val jobDescriptor: BackendJobDes
     if (referenceName.length <= 127) referenceName else referenceName.md5Sum
   }
 
+  private[jes] def findGlobOutputs(jobDescriptor: BackendJobDescriptor): Seq[WdlGlobFile] = {
```
Comment (mcovarr) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Does this need to use a `Seq` or `List` in all the types?  It doesn't appear that order is important.

**Comment by mcovarr** [comment]
:+1:

**Comment by Horneth** [comment]
👍

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala (hunk 9 above)
Comment (geoffjentry) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: I find it amusing that you're against extra type safety because you hate the extra keystrokes of `foo.x` instead of `x` but you love typing `traversable` everywhere ;)
