### PR TITLE
Get the restart tests up and running. Closes #2866

### LINKED ISSUE #2866: Wom: Fix restart tests
This might be as simple as updating the "waited for" status from `Failed` to `Succeeded`, since we expect workflow success in the metadata.

And then reinstate centaur test:
- [ ] `restart_jes_with_recover`
- [ ] `restart_local_with_recover`
- [ ] `restart_tes_without_recover`

### PR DESCRIPTION
**Pull request by geoffjentry**

### CODE REVIEW

File: centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala [hunk 1]
```diff
@@ -121,7 +121,7 @@ object TestFormulas {
                              callMarker: CallMarker,
                              recover: Boolean,
                              finalStatus: TerminalStatus): Test[SubmitResponse] = {
-    cromwellRestart(workflowDefinition, callMarker, testRecover = recover, finalStatus = Failed)
+    cromwellRestart(workflowDefinition, callMarker, testRecover = recover, finalStatus = finalStatus)
```
Comment (cjllanwarne) [inline centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala]: 🤦‍♂️

Comment (mcovarr) [reply centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala]: `ignore`ance was bliss

**Comment by geoffjentry** [comment]
OK I think the TDD world is fucking wit me as code cov gave me a red mark with a 0% diff. Everyhing else is green, merging.
