### PR TITLE
Moar retries Closes #600

### LINKED ISSUE #600: 500 Internal error when trying to get task hash for call caching
These workflows all failed with the stacktrace error in the comments section. These were run on gotc-prod.

836783df-339e-4631-a7cd-038072899edb - operations/EIfzx8m1Khjt87q2wPLY8CAgn6KQ6Z4NKg9wcm9kdWN0aW9uUXVldWU

9925f072-debf-4e4c-98aa-01db0a34a62f - operations/EOqx-cy1KhioppLVjZKx1XQgn6KQ6Z4NKg9wcm9kdWN0aW9uUXVldWU

f7c465bb-e5e5-4cb8-b493-82f072a40040 - operations/EIL4ks21Khi1zfCMm4HHpO8BIJ-ikOmeDSoPcHJvZHVjdGlvblF1ZXVl

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by Horneth** [comment]
wheel @cjllanwarne @kshakir

File: engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala [hunk 1]
```diff
@@ -40,6 +40,17 @@ object GcsFileSystemProvider {
   // Then, at the end of this time, I decided to just pick some numbers arbitrarily.
   private val retryInterval = 500 milliseconds
   private val retryCount = 3
+
+  def withRetry[A](f: => A, retries: Int = retryCount): A = Try(f) match {
+    case Success(res) => res
+    case Failure(ex: GoogleJsonResponseException)
+      if retries > 0 &&
+        (ex.getStatusCode == 404 || ex.getStatusCode == 500) =>
+      // FIXME remove this sleep
```
Comment (cjllanwarne) [inline engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala]: FIXME when?

File: engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala [hunk 2]
```diff
@@ -40,6 +40,17 @@ object GcsFileSystemProvider {
   // Then, at the end of this time, I decided to just pick some numbers arbitrarily.
```
Comment (cjllanwarne) [inline engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala]: :smiley:

File: engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala (hunk 1 above)
Comment (Horneth) [inline engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala]: Hopefully soon - Fixing this is a bigger refactoring than this ticket which is just a "get this into the next release to reduce failure on transient google errors"

Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala]: Asyncing this will be a whole lot easier in our actorified imminent future

**Comment by cjllanwarne** [comment]
:+1:

**Comment by kshakir** [comment]
_such quick. much dirty._ :dog: :+1:

File: engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala [hunk 3]
```diff
@@ -82,26 +93,10 @@ class GcsFileSystemProvider private (storageClient: Try[Storage], executionConte
...
-          Thread.sleep(retryInterval.toMillis.toInt)
-          tryExists(retries - 1)
-        case Failure(ex: GoogleJsonResponseException) if ex.getStatusCode == 404 => false
-        case Failure(ex) => throw ex
-      }
-
-      if (!tryExists(retryCount)) throw new FileNotFoundException(path.toString)
+      Try(withRetry(client.objects.get(gcsPath.bucket, gcsPath.objectName).execute)) recover {
+        case ex: GoogleJsonResponseException
+          if ex.getStatusCode == 404 && !gcsPath.isDirectory => throw new FileNotFoundException(path.toString)
```
Comment (Horneth) [inline engine/src/main/scala/cromwell/engine/backend/io/filesystem/gcs/GcsFileSystemProvider.scala]: So I realize now this won't work, because it will still throw an exception if gcsPath is a directory on the `get` call below. Since gcs directories never really "exist", `execute` will return 404, although in order for the Nio magic to work we can't throw a FileNotFound exception every time we manipulate directories.
This should be 
```scala
if ex.getStatusCode == 404 => 
   if (!gcsPath.isDirectory) throw new FileNotFoundException(path.toString)
```
I can't fix it right now but I'll try to do it later tonight or tomorrow.
If for some reason I can't and someone take back this PR, don't forget to change this before merging :)
