### PR TITLE
Double Quoted file inputs cause PipelineAPI workflows to run forever. Closes #2178

### LINKED ISSUE #2178: Cromwell doesn't fail workflow with bad inputs
A workflow was submitted and the inputs looked like:
```
"inputs": {
    "HaplotypeCallerGvcfScatterWf.ref_dict": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.dict\"",
    "HaplotypeCallerGvcfScatterWf.MergeVCFs.disk_size": 10,
    "HaplotypeCallerGvcfScatterWf.HaplotypeCaller.mem_size": "4 GB",
    "HaplotypeCallerGvcfScatterWf.ref_fasta": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta\"",
    "HaplotypeCallerGvcfScatterWf.ref_fasta_index": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta.fai\"",
    "HaplotypeCallerGvcfScatterWf.input_bam_index": "gs://gatk-tutorials/workshop_1702/variant_discovery/data/bams/father.bai",
    "HaplotypeCallerGvcfScatterWf.HaplotypeCaller.interval_padding": 100,
    "HaplotypeCallerGvcfScatterWf.MergeVCFs.mem_size": "2 GB",
    "HaplotypeCallerGvcfScatterWf.scattered_calling_intervals_list": "gs://gatk-test-data/intervals/b37_wgs_scattered_calling_intervals.txt",
    "HaplotypeCallerGvcfScatterWf.input_bam": "gs://gatk-tutorials/workshop_1702/variant_discovery/data/bams/father.bam",
    "HaplotypeCallerGvcfScatterWf.HaplotypeCaller.disk_size": 100
  },
```
Cromwell started jobs but they don't have operations IDs and the jobs/workflow remain in the "Running" state forever. Ideally the workflow should fail, and fail gracefully with an error message that makes sense. This ticket can be easily reproduced on 25_hotfix by corrupting a file input path to look like:
```
"HaplotypeCallerGvcfScatterWf.ref_fasta_index": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta.fai\"",
```

### PR DESCRIPTION
**Pull request by jsotobroad**
JesApi run creation failures were being caught by the JesApi status handler and not getting handled correctly.

### CODE REVIEW

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala [hunk 1]
```diff
@@ -53,13 +53,16 @@ class JesApiQueryManager(val qps: Int Refined Positive) extends Actor with Actor
...
       val delay = nextRequest.backoff.backoffMillis.millis
       context.system.scheduler.scheduleOnce(delay, self, nextRequest)
       ()
-    case JesApiQueryFailed(request, _) =>
-      request.requester ! failure
+    case JesApiQueryStatusFailed(request, cause) =>
+      request.requester ! JesApiQueryStatusFailed(request, cause)
+      ()
+    case JesApiQueryCreationFailed(request, cause) =>
+      request.requester ! JesApiQueryCreationFailed(request, cause)
```
Comment (Horneth) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala]: I don't think you need to differentiate those 2 cases here as both `JesApiQueryStatusFailed` and `JesApiQueryCreationFailed` extend `JesApiQueryFailed` and you're doing the same thing for both.
It could just be

```scala
case failure: JesApiQueryFailed =>
     request.requester ! failure
```

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/StatusPolling.scala [hunk 2]
```diff
@@ -29,7 +29,7 @@ private[statuspolling] trait StatusPolling { this: JesPollingActor =>
     }
 
     override def onFailure(e: GoogleJsonError, responseHeaders: HttpHeaders): Unit = {
-      pollingManager ! JesApiQueryFailed(originalRequest, new JesApiException(GoogleJsonException(e, responseHeaders)))
+      pollingManager ! JesApiQueryCreationFailed(originalRequest, new JesApiException(GoogleJsonException(e, responseHeaders)))
```
Comment (Horneth) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/StatusPolling.scala]: Shouldn't this one be `JesApiQueryStatusFailed` ?

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala (hunk 1 above)
Comment (jsotobroad) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala]: 👍  much nicer

**Comment by Horneth** [comment]
👍

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/StatusPolling.scala (hunk 2 above)
Comment (jsotobroad) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/StatusPolling.scala]: i have no idea how i made this mistake....

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala [hunk 3]
```diff
@@ -101,7 +101,12 @@ class JesApiQueryManager(val qps: Int Refined Positive) extends Actor with Actor
         log.error(s"The JES API worker actor $terminee unexpectedly terminated while conducting ${work.workBatch.tail.size + 1} polls. Making a new one...")
         workInProgress -= terminee
         work.workBatch.toList.foreach { toResubmit =>
-          self ! JesApiQueryFailed(toResubmit, new JesApiException(cause))
+           toResubmit match {
```
Comment (danbills) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala]: I think you can omit `toResubmit => toResubmit match` and it will still work.  I.e. just submit the partial function

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala [hunk 4]
```diff
@@ -53,13 +53,13 @@ class JesApiQueryManager(val qps: Int Refined Positive) extends Actor with Actor
...
-      val nextRequest = request.withFailedAttempt
+    case failed: JesApiQueryFailed if failed.query.failedAttempts < maxRetries =>
+      val nextRequest = failed.query.withFailedAttempt
       val delay = nextRequest.backoff.backoffMillis.millis
       context.system.scheduler.scheduleOnce(delay, self, nextRequest)
       ()
-    case JesApiQueryFailed(request, _) =>
-      request.requester ! failure
+    case failure: JesApiQueryFailed =>
+      failure.query.requester ! failure
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala]: I know I wrote it originally, but this whole `match` should probably just be an `if` statement. e.g.
```
handleQueryFailure(failure: JesApiQueryFailed) = if (failure.query.failedAttempts > maxRetries) {
...
} else {
...
}
```

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala [hunk 5]
```diff
@@ -158,12 +163,24 @@ object JesApiQueryManager {
...
 
-  final case class GoogleJsonException(e: GoogleJsonError, responseHeaders: HttpHeaders) extends IOException with CromwellFatalExceptionMarker
-  final class JesApiException(e: Throwable) extends RuntimeException(e) with CromwellFatalExceptionMarker
-  final case class JesApiQueryFailed(query: JesApiQuery, cause: JesApiException)
+  final case class GoogleJsonException(e: GoogleJsonError, responseHeaders: HttpHeaders) extends IOException with CromwellFatalExceptionMarker {
+    override def getMessage: String = e.getMessage
+  }
+
+  final class JesApiException(e: Throwable) extends RuntimeException(e) with CromwellFatalExceptionMarker {
+    override def getMessage: String = "Unable to Complete JES Api Request"
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala]: Decapitalize `Complete` => `complete`

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesStatusRequestClient.scala [hunk 6]
```diff
@@ -23,7 +23,7 @@ trait JesStatusRequestClient { this: Actor with ActorLogging =>
     case r: RunStatus =>
       log.debug(s"Polled status received: $r")
       completePromise(Success(r))
-    case JesApiQueryFailed(_, e) =>
+    case JesApiQueryStatusFailed(_, e) =>
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesStatusRequestClient.scala]: ToL: I prefer `JesApiStatusQueryFailed` to `JesApiQueryStatusFailed`

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/RunCreation.scala [hunk 7]
```diff
@@ -22,7 +22,7 @@ private[statuspolling] trait RunCreation { this: JesPollingActor =>
     }
 
     override def onFailure(e: GoogleJsonError, responseHeaders: HttpHeaders): Unit = {
-      pollingManager ! JesApiQueryFailed(originalRequest, new JesApiException(GoogleJsonException(e, responseHeaders)))
+      pollingManager ! JesApiQueryCreationFailed(originalRequest, new JesApiException(GoogleJsonException(e, responseHeaders)))
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/RunCreation.scala]: ToL: Also prefer `JesApiCreationQueryFailed` to `JesApiQueryCreationFailed`

**Comment by cjllanwarne** [comment]
👍

**Comment by jsotobroad** [comment]
Should I keep the error message to `JES` or should it say `Pipelies API`

**Comment by geoffjentry** [comment]
I'd stick w/ JES for now. I have #2019 open to do a more holistic replacement

**Comment by cjllanwarne** [comment]
Re-👍

**Comment by danbills** [comment]
👍

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala [hunk 8]
```diff
@@ -52,15 +52,14 @@ class JesApiQueryManager(val qps: Int Refined Positive) extends Actor with Actor
...
-      request.requester ! failure
-      ()
+  private def handleQueryFailure(failure: JesApiQueryFailed) = if (failure.query.failedAttempts < maxRetries) {
+    val nextRequest = failure.query.withFailedAttempt
+    val delay = nextRequest.backoff.backoffMillis.millis
+    context.system.scheduler.scheduleOnce(delay, self, nextRequest)
+    ()
+  } else {
+    failure.query.requester ! failure
+    ()
```
Comment (Horneth) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/statuspolling/JesApiQueryManager.scala]: Super nit pick: I don't think you need this `()`, the `!` already returns `Unit`

**Comment by Horneth** [comment]
re 👍
