### PR TITLE
Don't let Cromwell start if a service fails to load. Closes #896

### LINKED ISSUE #896: Error handling when Service Registry fails to initialize (e.g. bad config)
If the service registry fails to get instantiated (wrong service classpath in the conf...), an exception is thrown but Cromwell still starts and an ActorRef is available in  the `serviceRegistryActor` field, although the actor itself doesn't exist. All messages to the service registry are then lost.

### PR DESCRIPTION
**Pull request by geoffjentry**
o Pull ServiceRegistryActor into main actor system.
o Remove ServiceRegistryClient
o Create a CromwellRootActor to act as a guardian for other top level actors
o Move WorkflowLogCopyActor to be a top level actor
o Numerous small cleanups, IntelliJ requests, etc

### CODE REVIEW

**Comment by geoffjentry** [comment]
Welcoming all comers as this is hefty but @Horneth in particular - a lot of the rebase-a-palooza involved changes you had made so an extra pair of eyes to make sure I didn't undo something would be good.

File: engine/src/main/scala/cromwell/server/CromwellRootActor.scala [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+import cromwell.engine.workflow.{WorkflowManagerActor, WorkflowStoreActor}
+import cromwell.services.ServiceRegistryActor
+import lenthall.config.ScalaConfig.EnhancedScalaConfig
+
+/**
+  * An actor which serves as the lord protector for the rest of Cromwell, allowing us to have more fine grain
+  * control on top level supervision, etc.
+  *
+  * For now there are only two (non-test) entry points into Cromwell - either using SingleWorkflowRunnerActor or CromwellServerActor.
+  * This is intended to be mixed in with those entry points.
```
Comment (mcovarr) [inline engine/src/main/scala/cromwell/server/CromwellRootActor.scala]: mixed in?

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala [hunk 2]
```diff
@@ -23,12 +23,15 @@ case class JesBackendLifecycleActorFactory(configurationDescriptor: BackendConfi
   val jesConfiguration = new JesConfiguration(configurationDescriptor)
 
   override def workflowInitializationActorProps(workflowDescriptor: BackendWorkflowDescriptor,
-                                                calls: Seq[Call]): Option[Props] = {
-    Option(JesInitializationActor.props(workflowDescriptor, calls, jesConfiguration).withDispatcher("akka.dispatchers.backend-dispatcher"))
+                                                calls: Seq[Call],
+                                                serviceRegistryActor: ActorRef): Option[Props] = {
+    Option(JesInitializationActor.props(workflowDescriptor, calls, jesConfiguration, serviceRegistryActor).withDispatcher("akka.dispatchers.backend-dispatcher"))
```
Comment (mcovarr) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala]: why isn't there a constant for these dispatcher names?

Comment (geoffjentry) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala]: Because @Horneth is super lazy!!!!!!

Comment (Horneth) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala]: That's correct

Comment (geoffjentry) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala]: I can put it in, this PR already is a touch kitchen sinky anyways, what's another little thing

File: engine/src/main/scala/cromwell/server/CromwellRootActor.scala (hunk 1 above)
Comment (geoffjentry) [inline engine/src/main/scala/cromwell/server/CromwellRootActor.scala]: At one point it was a trait

Comment (mcovarr) [inline engine/src/main/scala/cromwell/server/CromwellRootActor.scala]: it's all growed up now

Comment (geoffjentry) [inline engine/src/main/scala/cromwell/server/CromwellRootActor.scala]: technically it's less grown as abstract class is less powerful ;)

File: engine/src/test/scala/cromwell/CallCachingWorkflowSpec.scala [hunk 3]
```diff
@@ -142,17 +142,12 @@ class CallCachingWorkflowSpec extends CromwellTestkitSpec {
     }
 
     "show valid values for call caching in metadata" taggedAs PostMVP ignore {
-      implicit val workflowManagerActor = TestActorRef(
-        new WorkflowManagerActor(CallCachingWorkflowSpec.callCachingConfig, system.actorOf(WorkflowStoreActor.props))
-      )
-
+      // FIXME: I believe the WMA no longer needs to be special made but this test is ignored so not sure
```
Comment (mcovarr) [inline engine/src/test/scala/cromwell/CallCachingWorkflowSpec.scala]: special made?

Comment (geoffjentry) [inline engine/src/test/scala/cromwell/CallCachingWorkflowSpec.scala]: <--- There was a WMA being made for this test

**Comment by mcovarr** [comment]
:+1:

File: src/main/scala/cromwell/Main.scala [hunk 4]
```diff
@@ -86,10 +86,10 @@ object Main extends App {
   } yield action
 }
 
-class Main private[cromwell](managerSystem: WorkflowManagerSystem) {
+class Main private[cromwell](managerSystem: CromwellSystem) {
```
Comment (Horneth) [inline src/main/scala/cromwell/Main.scala]: rename to `cromwellSystem` ?

**Comment by Horneth** [comment]
LGTM 👍  (note the fair play of this 👍  which is equivalent to punching myself in the face multiple times as I will have to rebase 😭  )

**Comment by geoffjentry** [comment]
You are a modern day saint @horneth

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala (hunk 2 above)
Comment (geoffjentry) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala]: Actually I'll do this as a separate PR as I'm also super lazy

File: engine/src/test/scala/cromwell/CallCachingWorkflowSpec.scala (hunk 3 above)
Comment (cjllanwarne) [inline engine/src/test/scala/cromwell/CallCachingWorkflowSpec.scala]: I believe he was commenting on your grammar rather than the FIXME's basic sentiment

Comment (geoffjentry) [inline engine/src/test/scala/cromwell/CallCachingWorkflowSpec.scala]: I was just being cheeky. I've changed it already

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala (hunk 2 above)
Comment (geoffjentry) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesBackendLifecycleActorFactory.scala]: I take that back, since i'm waiting on @Horneth anyways i'll just do it
