### PR TITLE
caching bug fix closes #1461

### LINKED ISSUE #1461: Detritus copy fails on Local backend (and presumably all SFS). Might be scatter related
EDIT: The final (non-scattered) task didn't print out the ` Failed copying cache results, falling back to running job` message but the timing diagram shows that it clearly transitioned quickly from BackendIsCopyingCallCacheOutputs to spend the same time "RunningJob" as everything else.

Happened for all the scatters of a hello world workflow:
```
2016-09-20 18:53:47,051 cromwell-system-akka.dispatchers.engine-dispatcher-37 ERROR - helloArray.helloWorld:79:1: Failed copying cache results, falling back to running job: java.lang.RuntimeException: The call detritus files for source cache hit aren't found for call helloArray.helloWorld
2016-09-20 18:53:47,052 cromwell-system-akka.dispatchers.backend-dispatcher-66 INFO  - SharedFileSystemAsyncJobExecutionActor [UUID(55d1e515)helloArray.helloWorld:79:1]: `echo "hello, world"`
2016-09-20 18:53:47,053 cromwell-system-akka.dispatchers.backend-dispatcher-66 INFO  - SharedFileSystemAsyncJobExecutionActor [UUID(55d1e515)helloArray.helloWorld:79:1]: executing: /bin/bash /Users/chrisl/IdeaProjects/cromwell/cromwell-executions/helloArray/55d1e515-90fb-4d96-a025-b19a7decd1f4/call-helloWorld/shard-79/execution/script
2016-09-20 18:53:47,053 cromwell-system-akka.dispatchers.backend-dispatcher-66 INFO  - SharedFileSystemAsyncJobExecutionActor [UUID(55d1e515)helloArray.helloWorld:79:1]: command: "/bin/bash" "/Users/chrisl/IdeaProjects/cromwell/cromwell-executions/helloArray/55d1e515-90fb-4d96-a025-b19a7decd1f4/call-helloWorld/shard-79/execution/script.submit"
2016-09-20 18:53:47,059 cromwell-system-akka.dispatchers.backend-dispatcher-66 INFO  - SharedFileSystemAsyncJobExecutionActor [UUID(55d1e515)helloArray.helloWorld:79:1]: job id: 89817
2016-09-20 18:53:47,907 cromwell-system-akka.dispatchers.engine-dispatcher-37 INFO  - WorkflowExecutionActor-55d1e515-90fb-4d96-a025-b19a7decd1f4 [UUID(55d1e515)]: Job helloArray.helloWorld:79:1 succeeded!
```

The workflow:
```
task helloWorld {
    command { echo "hello, world" }
    output { String s = read_string(stdout()) }
}

task mirror {
	Array[String] s
	command {}
	output { Array[String] out = s }
}

workflow helloArray {
	Array[Int] ints = range(100)
	scatter(i in ints) {
	    call helloWorld
	}
	call mirror { input: s = helloWorld.s }

}
```

### PR DESCRIPTION
**Pull request by ruchim**
making sure the detritus callRootPath is present for cache hit calls

### CODE REVIEW

File: backend/src/main/scala/cromwell/backend/callcaching/CacheHitDuplicating.scala [hunk 1]
```diff
@@ -79,7 +79,7 @@ trait CacheHitDuplicating {
       (fileKey, destinationPath.toString)
     }
 
-    destinationJobDetritusFiles.toMap
+    destinationJobDetritusFiles.toMap ++ Map(JobPaths.CallRootPathKey -> destinationCallRootPath)
```
Comment (mcovarr) [inline backend/src/main/scala/cromwell/backend/callcaching/CacheHitDuplicating.scala]: I think you can just 

```scala
destinationJobDetritusFiles.toMap + (JobPaths.CallRootPathKey -> destinationCallRootPath)
```

Comment (mcovarr) [inline backend/src/main/scala/cromwell/backend/callcaching/CacheHitDuplicating.scala]: Were you or @cjllanwarne able to test this?

Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/callcaching/CacheHitDuplicating.scala]: I'll try it out

**Comment by cjllanwarne** [comment]
Looks like it's all good in the database now 👍

**Comment by cjllanwarne** [comment]
ToL: could we not store the callRootPath prefix in the `result_metainfo` table since it's required and a single element, and not really detritus?

**Comment by ruchim** [comment]
@cjllanwarne -- great suggestion, but I want to make the least amount of possible changes pre-release. I can ticket it
@mcovarr other than re-starting the JES build, is there anything else require to get a thumb?

**Comment by mcovarr** [comment]
:+1:
