### PR TITLE
Common globbing behavior between SFS & JES closes #1341 closes #1245

### LINKED ISSUE #1245: glob() broken in typical use cases (local)
From [this issue on the GATK forums](http://gatkforums.broadinstitute.org/wdl/discussion/8095/glob-function-is-inconsistent-between-jes-backend-and-local).

Using the WDL file from that example, I run the WDL and get this for the output of `makeFilesTask`:

```
/Users/sfrazer/projects/cromwell/cromwell-executions/globTestWorkflow/baa45456-4ff4-4c03-84b3-2df0c9bb9e0b/call-makeFilesTask
├── Reads
│   ├── four.unique.txt
│   └── three.unique.txt
├── one.unique.txt
├── rc
├── script
├── stderr
├── stdout
└── two.unique.txt
```

It seems that the [globbing code in Cromwell](https://github.com/broadinstitute/cromwell/blob/3f81d4e4ad52f9a551f190d8a40beac241d77f0e/supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemExpressionFunctions.scala#L65) uses `.glob(s"**/$pattern")`, which in this case would expand to `.glob(s"**/./Reads/*.unique.txt")`.  For reference here is the [documentation for the Java pattern matcher](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher%28java.lang.String%29)

Testing this out via the Scala REPL:

```
scala> import java.nio.file.Paths
import java.nio.file.Paths

scala> import better.files._
import better.files._

scala> val p = Paths.get("/Users/sfrazer/projects/cromwell/cromwell-executions/globTestWorkflow/baa45456-4ff4-4c03-84b3-2df0c9bb9e0b/call-makeFilesTask")
p: java.nio.file.Path = /Users/sfrazer/projects/cromwell/cromwell-executions/globTestWorkflow/baa45456-4ff4-4c03-84b3-2df0c9bb9e0b/call-makeFilesTask

scala> p.glob("**./Reads/*.unique.txt").map(_.name).foreach(println)

scala> p.glob("./Reads/*.unique.txt").map(_.name).foreach(println)

scala> p.glob("**/Reads/*.unique.txt").map(_.name).foreach(println)
four.unique.txt
three.unique.txt

scala> p.glob("**/*.unique.txt").map(_.name).foreach(println)
one.unique.txt
four.unique.txt
three.unique.txt
two.unique.txt
```

Ideally, the user should be able to:
- Use pattern `./Reads/*.unique.txt` and retrieve `four.unique.txt` and `three.unique.txt`
- Use pattern `*.unique.txt` and retrieve `one.unique.txt` and `two.unique.txt`

### LINKED ISSUE #1341: Glob function does not work with an absolute path
I am creating some output files(from terminal tasks) outside of the cromwell working directory. I still want to include them in task's output. However the glob function returns an empty array for the following call:
`Array[File] pngs=glob("/tmp/asmirnov/plots/*.png)`
even though there are png files in the directory.

I'm not sure whether this is an intended behavior or a bug. If it is intended, is there a workaround? 
Thank you!

### PR DESCRIPTION
**Pull request by ruchim**
- SFS now mimicks JES globbing

### CODE REVIEW

**Comment by Horneth** [comment]
Something seems off in the globbing centaur test metadata but otherwise 👍

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+import scala.collection.JavaConverters._
+import cromwell.core.path.PathImplicits._
+
+trait GlobFunctions extends PureStandardLibraryFunctionsLike {
+
+  def callContext: CallContext
+
+  def findGlobOutputs(call: TaskCall, jobDescriptor: BackendJobDescriptor): Set[WdlGlobFile] = {
+    val globOutputs = call.task.findOutputFiles(jobDescriptor.fullyQualifiedInputs, NoFunctions) collect {
+      case glob: WdlGlobFile => glob
```
Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: Can just use filter here

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 2]
```diff
@@ -219,7 +212,7 @@ class JesAsyncBackendJobExecutionActor(val jesParams: JesAsyncExecutionActorPara
   }
 
   private def generateJesGlobFileOutputs(wdlFile: WdlGlobFile): List[JesFileOutput] = {
-    val globName = callEngineFunctions.globName(wdlFile.value)
+    val globName = backendEngineFunctions.globName(wdlFile.value)
     val globDirectory = globName + "/"
     val globListFile = globName + ".list"
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: These two (`globDirectory` and `globFileList`) are also in `backendEngineFunctions` too

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala [hunk 3]
```diff
@@ -289,9 +283,13 @@ class JesAsyncBackendJobExecutionActor(val jesParams: JesAsyncExecutionActorPara
...
          |cd ${JesWorkingDisk.MountPoint}
          |$command
+         |)
+         |echo $$? > $rcTmpPath
+         |(
+         |cd ${JesWorkingDisk.MountPoint}
          |$globManipulations
          |)
-         |echo $$? > $rcPath
+         |mv $rcTmpPath $rcPath
```
Comment (cjllanwarne) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: Oops! Nice catch!

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala [hunk 4]
```diff
@@ -167,10 +167,25 @@ trait SharedFileSystemAsyncJobExecutionActor
     * Writes the script file containing the user's command from the WDL as well
     * as some extra shell code for monitoring jobs
     */
-  private def writeScript(instantiatedCommand: String, cwd: Path) = {
+  private def writeScript(instantiatedCommand: String, cwd: Path, globFiles: Set[WdlGlobFile]) = {
     val rcPath = if (isDockerRun) jobPaths.toDockerPath(jobPaths.returnCode) else jobPaths.returnCode
     val rcTmpPath = s"$rcPath.tmp"
 
+    def globManipulation(globFile: WdlGlobFile) = {
```
Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala]: This looks like a direct copy/paste? Maybe we can extract this into `backendEngineFunctions` too?

File: .travis.yml [hunk 5]
```diff
@@ -17,7 +17,7 @@ before_cache:
   - find $HOME/.sbt -name "*.lock" -delete
 env:
   global:
-    - CENTAUR_BRANCH=develop
+    - CENTAUR_BRANCH=rm_globbing
```
Comment (cjllanwarne) [inline .travis.yml]: Revert before merging

**Comment by cjllanwarne** [comment]
Sigh... And a thumb here too 👍

**Comment by cjllanwarne** [comment]
Some of the test failures seem very genuine... 😨

**Comment by ruchim** [comment]
I'm seeing a lot of this in the Cromwell logs:
```
cromwell.core.path.PathParsingException: java.lang.IllegalArgumentException: Could not find suitable filesystem among Default to parse gs://cloud-cromwell-dev/cromwell_execution/globbingBehavior/0f14036c-402e-4368-986b-6fb8baf512d1/call-writeFiles/glob-7bb0c33ac658a900e2c3804726fc1d2a/hello.txt.
	at cromwell.core.path.PathFactory$$anonfun$buildPath$5.apply(PathFactory.scala:49)
	at cromwell.core.path.PathFactory$$anonfun$buildPath$5.apply(PathFactory.scala:47)
	at scala.Option.getOrElse(Option.scala:121)
	at cromwell.core.path.PathFactory$.buildPath(PathFactory.scala:47)
	at cromwell.core.path.PathFactory$class.buildPath(PathFactory.scala:31)
	at cromwell.engine.WdlFunctions.buildPath(WdlFunctions.scala:10)
	at cromwell.backend.wdl.ReadLikeFunctions$class.readFile(ReadLikeFunctions.scala:31)
	at cromwell.engine.WdlFunctions.readFile(WdlFunctions.scala:10)
	at wdl4s.expression.WdlStandardLibraryFunctions$class.fileContentsToString(WdlStandardLibraryFunctions.scala:12)
	at cromwell.engine.WdlFunctions.fileContentsToString(WdlFunctions.scala:10)
	at cromwell.backend.wdl.ReadLikeFunctions$$anonfun$readContentsFromSingleFileParameter$1.apply(ReadLikeFunctions.scala:22)
	at cromwell.backend.wdl.ReadLikeFunctions$$anonfun$readContentsFromSingleFileParameter$1.apply(ReadLikeFunctions.scala:21)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at cromwell.backend.wdl.ReadLikeFunctions$class.readContentsFromSingleFileParameter(ReadLikeFunctions.scala:21)
	at cromwell.backend.wdl.ReadLikeFunctions$class.read_string(ReadLikeFunctions.scala:62)
	at cromwell.engine.WdlFunctions.read_string(WdlFunctions.scala:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at wdl4s.expression.WdlFunctions$$anonfun$getFunction$1.apply(WdlFunctions.scala:12)
	at wdl4s.expression.WdlFunctions$$anonfun$getFunction$1.apply(WdlFunctions.scala:12)
	at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:158)
	at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:85)
	at wdl4s.WdlExpression.evaluate(WdlExpression.scala:161)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processRunnableDynamicDeclaration(WorkflowExecutionActor.scala:433)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$18.apply(WorkflowExecutionActor.scala:362)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$18.apply(WorkflowExecutionActor.scala:353)
	at scala.collection.immutable.List.map(List.scala:273)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableScopes(WorkflowExecutionActor.scala:353)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.handleExecutionSuccess(WorkflowExecutionActor.scala:326)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$handleCallSuccessful(WorkflowExecutionActor.scala:304)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$3.applyOrElse(WorkflowExecutionActor.scala:97)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$3.applyOrElse(WorkflowExecutionActor.scala:82)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:663)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:33)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:33)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala (hunk 3 above)
Comment (ruchim) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala]: all thanks to a reviewer named @kshakir

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala (hunk 4 above)
Comment (ruchim) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala]: True -- we had in person discussion that much more can/should be abstracted, but I was going to file a future ticket for it, in the interest of time. However, I'll see what I can tweak once I get the test to pass.

**Comment by kcibul** [comment]
When we get back, please also make sure to update the documentation as well.  This is a breaking change (which is essential for consistency) but we should be super clear about that

**Comment by kshakir** [comment]
NOTE: This PR cannot be merged until https://github.com/broadinstitute/centaur/pull/124 is reviewed and merged.

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala (hunk 1 above)
Comment (kshakir) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: I like collect better than an explicit filter, then map from `WdlFile` to `WdlGlobFile`.

File: CHANGELOG.md [hunk 6]
```diff
@@ -4,6 +4,7 @@
 
 * When emitting workflow outputs to the Cromwell log only the first 1000 characters per output will be printed
 * Added support for conditional (`if`) statements.
+* Globs for Shared File System (SFS) backends, such as local or SGE, now use bash globbing instead of Java globbing, consistent with the JES backend.
```
Comment (cjllanwarne) [inline CHANGELOG.md]: `Consistent with "The WDL Spec"`. Also we should check that the WDL spec is consistent with "`The WDL Spec`"

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala (hunk 1 above)
Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: Oh I missed the cast to `WdlGlobFile`. Carry on!

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+    }
+
+    globOutputs.distinct.toSet
+  }
+
+  def globDirectory(glob: String): String = globName(glob) + "/"
+  def globName(glob: String) = s"glob-${glob.md5Sum}"
```
Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: (Massive ToL) Could these be `lazy val`s on `WdlGlobFile` to avoid constant recalculation?

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+
+  /**
+    * Returns a path to the glob using toRealString.
+    *
+    * NOTE: Due to use of toRealString, returned paths must be passed to PathBuilders.buildPath, and will not work with
+    * Paths.get.
+    *
+    * This path is usually passed back into the glob() method below.
```
Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: These two provisos make me feel like adding a @geoffjentry -like comment, along the lines of "well if it needs special handling it should be wrapped in an ADT"

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+    * @return The path converted using .toRealString.
+    */
+  override def globPath(glob: String): String = callContext.root.resolve(globDirectory(glob)).toRealString
+
+  /**
+    * Returns a list of path from the glob, each path converted to a string using toRealString.
+    *
+    * The paths are currently read from a list file based on the pattern, and the path parameter is not used.
+    *
+    * NOTE: Due to use of toRealString, returned paths must be passed to PathBuilders.buildPath, and will not work with
```
Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: Ditto

File: backend/src/main/scala/cromwell/backend/io/WorkflowPaths.scala [hunk 10]
```diff
@@ -18,20 +18,21 @@ trait WorkflowPaths extends PathFactory {
   def workflowDescriptor: BackendWorkflowDescriptor
   def config: Config
   
-  protected lazy val executionRootString = config.as[Option[String]]("root").getOrElse("cromwell-executions")
+  protected lazy val executionRootString: String = config.as[Option[String]]("root").getOrElse("cromwell-executions")
```
Comment (cjllanwarne) [inline backend/src/main/scala/cromwell/backend/io/WorkflowPaths.scala]: ToL: Also possibly suitable for an ADT?

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala [hunk 11]
```diff
@@ -47,7 +48,7 @@ object SharedFileSystem extends StrictLogging {
   private def localizePathViaCopy(originalPath: File, executionPath: File): Try[Unit] = {
     val action = Try {
       executionPath.parent.createDirectories()
-      val executionTmpPath = pathPlusSuffix(executionPath, ".tmp")
+      val executionTmpPath = pathPlusSuffix(executionPath, "tmp")
```
Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala]: :man_facepalming: oops!

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala [hunk 12]
```diff
@@ -23,7 +24,7 @@ object SharedFileSystem extends StrictLogging {
   import better.files._
 
   final case class AttemptedLookupResult(name: String, value: Try[WdlValue]) {
-    def toPair = name -> value
+    def toPair: (String, Try[WdlValue]) = name -> value
```
Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala]: Channeling @mcovarr, does the type annotation really add anything here?

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala [hunk 13]
```diff
@@ -167,21 +167,38 @@ trait SharedFileSystemAsyncJobExecutionActor
...
 
-#!/bin/sh
-(
- cd $cwd
- $instantiatedCommand
-)
-echo $$? > $rcTmpPath
-mv $rcTmpPath $rcPath
+      // TODO: Move glob list and directory generation into trait GlobFunctions? There is already a globPath using callContext
```
Comment (cjllanwarne) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala]: I'd say, "yes please!"

**Comment by cjllanwarne** [comment]
👍

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala (hunk 12 above)
Comment (mcovarr) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala]: Well nowadays it keeps IntelliJ from yellowing by default, though arguably we should turn off that default behavior if we don't like it.

**Comment by mcovarr** [comment]
:+1: I particularly like @cjllanwarne's ADT suggestions but I'd prefer to do that in a separate PR and not gate the release on that.

File: CHANGELOG.md (hunk 6 above)
Comment (kshakir) [inline CHANGELOG.md]: Scanning through, the spec doesn't say what a glob should match. This ticket, afaik, was only intended to standardize the behavior.

I'm going to say that updating the spec is a separate ticket.

File: backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala (hunk 8 above)
Comment (kshakir) [inline backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala]: Let's chat offline sometime soon, targeting post 24. I believe creating an ADT will require changes to wdl4s, as the glob functions are actually defined in traits there, and the wdl4s trait says glob returns a `String`.

I also hope that one day we _can_ get back to just using `Paths.get()` + `path.toString`, instead of our `List[PathBuilder]` and `path.toRealString`!

File: backend/src/main/scala/cromwell/backend/io/WorkflowPaths.scala (hunk 10 above)
Comment (kshakir) [inline backend/src/main/scala/cromwell/backend/io/WorkflowPaths.scala]: I'm definitely going to need more in real life discussion on this one going to an ADT. I do acknowledge that under the "s/he who last touched it" doctrine, I should know more about this, but in many ways, IntelliJ's auto fixer was the one who last touched this line, not me. ;)

**Comment by kshakir** [comment]
No current additions, just squashed into two commits, one for each contributor.

**Comment by vdauwera** [comment]
@ruchim Were you able to get to the bottom of the "Could not find suitable filesystem among Default to parse gs://..." errors you mention in the review thread? I'm hitting the same error when running a WDL on Google's wdl_runner, but the same WDL with the same inputs runs fine on the DSDE Methods Cromwell server (both C24 and C25). In my case the error occurs when using read_lines() on a gs:// filepath that points to a text file (list of file paths that I'd rather not include in the json for practical reasons). 

Also tagging friendly bug rotator @cjllanwarne

**Comment by ruchim** [comment]
@vdauwera I spotted the issue but it was @kshakir who ended up resolving it. I believe this had to do with the auth that was used to perform the read_* function, and not having access to the proper google credentials. I checked the [config](https://github.com/googlegenomics/pipelines-api-examples/blob/master/wdl_runner/cromwell_launcher/jes_template.conf) wdl_runner uses and I believe it's missing the goolge.auths key and the engine.filesystem.gcs.auth key in the config, which is probably what Cromwell requires to parse gcs files.

**Comment by vdauwera** [comment]
Oh, that's interesting -- thanks @ruchim. I'll discuss this with @mbookman.
