### PR TITLE
Better error messages for cyclic dependencies

### LINKED ISSUE #3143: Cromwell cyclic dependency error in 30.1, fine in 29
This workflow runs fine on "29-2caec7d" and fails with this stack trace on "30-a3ea825-SNAP" using the Pipelines API backend.

```
failures: [
{
causedBy: [
{
causedBy: [ ],
message: "This workflow contains a cyclic dependency on SomaticPairedEndSingleSampleWorkflow.$scatter_2"
},
{
causedBy: [ ],
message: "wdl.Scope.childGraphNodesSorted(Scope.scala:52)"
},
{
causedBy: [ ],
message: "wdl.Scope.childGraphNodesSorted$(Scope.scala:43)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.childGraphNodesSorted$lzycompute(WdlWorkflow.scala:63)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.childGraphNodesSorted(WdlWorkflow.scala:63)"
},
{
causedBy: [ ],
message: "wdl.WdlGraphNode$.buildWomGraph(WdlGraphNode.scala:140)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow$.womWorkflowDefinition(WdlWorkflow.scala:52)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.womDefinition$lzycompute(WdlWorkflow.scala:73)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.womDefinition(WdlWorkflow.scala:73)"
},
{
causedBy: [ ],
message: "wdl.WdlInputParsing$.buildWomExecutable(WdlInputParsing.scala:27)"
},
{
causedBy: [ ],
message: "wdl.WdlNamespaceWithWorkflow.womExecutable(WdlNamespace.scala:98)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.$anonfun$validateWdlNamespace$15(MaterializeWorkflowDescriptorActor.scala:493)"
},
{
causedBy: [ ],
message: "scala.util.Either.flatMap(Either.scala:338)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.$anonfun$validateWdlNamespace$13(MaterializeWorkflowDescriptorActor.scala:491)"
},
{
causedBy: [ ],
message: "scala.util.Either.flatMap(Either.scala:338)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.validateWdlNamespace(MaterializeWorkflowDescriptorActor.scala:490)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor(MaterializeWorkflowDescriptorActor.scala:231)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.$anonfun$applyOrElse$1(MaterializeWorkflowDescriptorActor.scala:157)"
},
{
causedBy: [ ],
message: "scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)"
},
{
causedBy: [ ],
message: "scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)"
},
{
causedBy: [ ],
message: "scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)"
},
{
causedBy: [ ],
message: "akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)"
},
{
causedBy: [ ],
message: "akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)"
},
{
causedBy: [ ],
message: "scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)"
},
{
causedBy: [ ],
message: "scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)"
},
{
causedBy: [ ],
message: "akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)"
},
{
causedBy: [ ],
message: "akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)"
},
{
causedBy: [ ],
message: "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"
}
],
message: "Workflow input processing failed"
}
],
```

I think the culprit has something to do with both the root and sub workflow both having a task called `GatherbamFiles` because when I renamed the task in the subworkflow (and all subsequent necessary renames) the workflow ran fine.  When I tried to make a simple example of this I couldn't get the error to pop up again so I'm definitely missing some nuances of the cause.  The root workflow passes womtool-30.1.jar validation.

Root workflow - [SomaticPairedSingleSampleWf.txt](https://github.com/broadinstitute/cromwell/files/1635810/SomaticPairedSingleSampleWf.txt)

Sub workflow - [SplitLargeRG.txt](https://github.com/broadinstitute/cromwell/files/1635814/SplitLargeRG.txt)

Dependencies zip - [SomaticPairedSingleSampleWfDependencies.zip](https://github.com/broadinstitute/cromwell/files/1635815/SomaticPairedSingleSampleWfDependencies.zip)

Let me know if theres any more information that might be useful.

### LINKED ISSUE #3885: Hard to debug cyclic dependency
This workflow reports a cyclic dependency but (a) it probably shouldn't and (b) it's super hard to debug:

https://github.com/broadinstitute/dsde-pipelines/blob/develop/genomes_in_the_cloud/single_sample/somatic/SomaticPairedSingleSampleWf.wdl

### PR DESCRIPTION
**Pull request by cjllanwarne**
Adds much better messages for debugging cyclic dependencies

- Closes #3885 
- Closes #3143

### CODE REVIEW

File: wdl/model/draft2/src/main/scala/wdl/draft2/model/Scope.scala [hunk 1]
```diff
@@ -41,17 +43,20 @@ trait Scope {
   }
 
   lazy val childGraphNodes: Set[WdlGraphNode] = children.toSet.filterByType[WdlGraphNode]
-  lazy val childGraphNodesSorted: List[WdlGraphNode] = {
+  lazy val childGraphNodesSorted: ErrorOr[List[WdlGraphNode]] = {
```
Comment (danbills) [inline wdl/model/draft2/src/main/scala/wdl/draft2/model/Scope.scala]: IMO this should be `Either` as `Validated` is not a Monad and we are flatMap-ing in violation of FP statute 1,000,004.

(Acknowledging this has ripple effects upward and would be painful)

File: wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/graph/LinkedGraphMaker.scala [hunk 2]
```diff
@@ -40,11 +40,26 @@ object LinkedGraphMaker {
   }
 
   def getOrdering(linkedGraph: LinkedGraph): ErrorOr[List[WorkflowGraphElement]] = {
+
+    def nodeName(workflowGraphElement: WorkflowGraphElement): String = workflowGraphElement.toWdlV1.lines.toList.head.replace("\"", "")
```
Comment (danbills) [inline wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/graph/LinkedGraphMaker.scala]: `.head` :see_no_evil:
