### PR TITLE
Fmc 725 validation exp eval. Closes #725.

### LINKED ISSUE #725: Backend validation expression evaluation exceptions
Class: BackendWorkflowInitializationActor
Line: 115
Function: evaluateRuntimeAttributesWdlExpressions
Code: TryUtils.sequenceMap(evaluateAttrs, "Runtime attributes evaluation").get

This line is producing an exception when it cannot evaluate an expression in runtime attributes.
There are open questions to work on:
Should this catch exception and log or just fail here?
If the case it catch the exception and log, should this return 'InitializationSuccess' after that? or just fail and return a InitializationFailed?

Use case: task1 output is the input for task2 and that value is used within RuntimeAttributes."

One this is solve, enable ignored test case.

### PR DESCRIPTION
**Pull request by francares**
Main purpose of this PR is to validate the idea of "Runtime Attributes validation" at Backend **initialization** an **execution** level.

[x] LocalBackend
- Initialization => No runtime attribute keys validation. Just a warning for those attributes that are not supported.
- Execution => Validate values of supported runtime attributes.

[x] JesBackend
- Initialization => Validate Docker key is present and warn for those attributes that are not supported.
- Execution => Validate values of supported runtime attributes.

[x] HtCondorBackend
- Initialization => No runtime attribute keys validation. Just a warning for those attributes that are not supported.
- Execution => Validate values of supported runtime attributes.

[x] SgeBackend
- Initialization => No runtime attribute keys validation. Just a warning for those attributes that are not supported.
- Execution => Validate values of supported runtime attributes.

The idea is to have this public while I implement this functionality so we all are in the same page.

### CODE REVIEW

**Comment by francares** [comment]
Reviewers: @geoffjentry and @Horneth.

**Comment by geoffjentry** [comment]
👍 

Once the dust settles w/ PBE I think we should go back and abstract common validation patterns which might exist across the backends into some place of optional utility functions for other backend implementers but that's not for now IMO

File: supportedBackends/htcondor/src/main/scala/cromwell/backend/impl/htcondor/HtCondorInitializationActor.scala [hunk 1]
```diff
@@ -35,20 +32,21 @@ class HtCondorInitializationActor(override val workflowDescriptor: BackendWorkfl
...
     Future {
-      val docker = validateDocker(runtimeAttributes.get(Docker), "Failed to get Docker mandatory key from runtime attributes".failureNel)
-      val failOnStderr = validateFailOnStderr(runtimeAttributes.get(FailOnStderr), FailOnStderrDefaultValue.successNel)
-      val continueOnReturnCode = validateContinueOnReturnCode(runtimeAttributes.get(ContinueOnReturnCode),
-        ContinueOnReturnCodeSet(Set(ContinueOnRcDefaultValue)).successNel)
-      (docker |@| failOnStderr |@| continueOnReturnCode) {
-        (_, _, _)
+      calls foreach { call =>
+        val runtimeAttributes = call.task.runtimeAttributes.attrs
+        val supportedKeys = Set(Docker, FailOnStderr, ContinueOnReturnCode)
```
Comment (Horneth) [inline supportedBackends/htcondor/src/main/scala/cromwell/backend/impl/htcondor/HtCondorInitializationActor.scala]: The list of supported keys could be moved to the `object` instead of being re-instantiated every time

File: supportedBackends/htcondor/src/main/scala/cromwell/backend/impl/htcondor/HtCondorInitializationActor.scala [hunk 2]
```diff
@@ -35,20 +32,21 @@ class HtCondorInitializationActor(override val workflowDescriptor: BackendWorkfl
...
+        val notSupportedAttributes = runtimeAttributes filterKeys {
+          !supportedKeys.contains(_)
+        }
+
+        if (notSupportedAttributes.size > 0) {
```
Comment (Horneth) [inline supportedBackends/htcondor/src/main/scala/cromwell/backend/impl/htcondor/HtCondorInitializationActor.scala]: `!notSupportedAttributes.isEmpty` seems a bit more idiomatic but not a big deal

**Comment by Horneth** [comment]
A couple nitpicks but 👍
