### PR TITLE
REDO: Handle ActorInitializationException in supervisors Closes #1079 (#1084)

### LINKED ISSUE #1079: Workflow gets stuck in Initialization if BackendWorkflowInitializationActor crashe during instantiation
If `BackendWorkflowInitializationActor` fails to instantiate, it never receives the `Initialize` message and the WorkflowActor never gets a response. So the workflow hangs forever.

From a more general perspective, if any actor in the lifecycle craches/dies unexpectedly, the workfow will hang at whichever state it was in..

### PR DESCRIPTION
**Pull request by cjllanwarne**
With apologies to @Horneth, I merged too soon! This unfortunately caused  `sbt "test-only cromwellSimpleWorkflowActorSpec"` to hang indefinitely.

* Lazy-fiy workflowPaths to prevent actor from throwing during instantiation

* Handle ActorInitFailure with supervision

* with default'

* cleanup Workflow finalization

* clean imports

* PR commnet

### CODE REVIEW

File: engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala [hunk 1]
```diff
@@ -137,6 +137,8 @@ class WorkflowManagerActor(config: Config)
     /*
      Responses from services
      */
+      // TODO Restart: to be verified after restart is implemented but these WorkflowSucceededResponse/WorkflowFailedResponse seem useless
```
Comment (mcovarr) [inline engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala]: TODO PBE will make this easier to find in a future sweep

File: supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesFinalizationActor.scala [hunk 2]
```diff
@@ -40,9 +39,7 @@ class JesFinalizationActor (override val workflowDescriptor: BackendWorkflowDesc
 
   private def deleteAuthenticationFile(): Future[Unit] = {
     if (jesConfiguration.needAuthFileUpload) {
-      val delete = () => Future(workflowPaths.gcsAuthFilePath.delete(false))
-
-      Retry.withRetry(delete, isFatal = isFatalJesException, isTransient = isTransientJesException)(context.system) map { _ => () }
+      Future(workflowPaths.gcsAuthFilePath.delete(false)) map { _ => () }
```
Comment (mcovarr) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesFinalizationActor.scala]: I'm going to guess there's already a sufficient layer of retries in the GCS filesystem code?

Comment (Horneth) [inline supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesFinalizationActor.scala]: Yes - every GCS operation is retried 3 times.

**Comment by mcovarr** [comment]
:+1:

**Comment by cjllanwarne** [comment]
👍 I'd also lobby for this to be part of the "Miguel explains big/exciting changes" thing on Friday, except maybe not force @mcovarr to explain it... This looks like a pattern we should use more often
