### PR TITLE
Autodetect & allow tabs in command blocks

### LINKED ISSUE #4051: Tabs whtitespace does not work
When I try to use tabs as whitespace in cromwell I'm getting a error:
```
[2018-08-29 09:25:20,10] [error] WorkflowManagerActor Workflow 1ed0e19c-fa18-4241-8f6b-0b72e181f59a failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Boxed Error
```

The specs say this should be possible, 0x9 == tab:
https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#whitespace-strings-identifiers-constants

I have tested cromwell 34 and the current develop branch (ce27a93).

wdl file that I used (replaced '\t' with '\<tab\>')
```
version 1.0

workflow Test {
<tab>input {
<tab><tab>
<tab>}

<tab>call Echo as echo {
<tab>input:
<tab>}

<tab>output {
<tab>}
}

task Echo {
<tab>input {
<tab>}

<tab>command {
<tab><tab>kill -9 $$
<tab><tab>echo test
<tab>}

<tab>output {
<tab>}
}
```

Full stacktrace:
```
[2018-08-29 09:25:20,10] [error] WorkflowManagerActor Workflow 1ed0e19c-fa18-4241-8f6b-0b72e181f59a failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Boxed Error
scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:280)
scala.concurrent.Promise.complete(Promise.scala:49)
scala.concurrent.Promise.complete$(Promise.scala:48)
scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
scala.concurrent.Promise.failure(Promise.scala:100)
scala.concurrent.Promise.failure$(Promise.scala:100)
scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:183)
cats.effect.IO.$anonfun$unsafeToFuture$2(IO.scala:341)
scala.util.Either.fold(Either.scala:189)
cats.effect.IO.$anonfun$unsafeToFuture$1(IO.scala:341)
cats.effect.IO.$anonfun$unsafeToFuture$1$adapted(IO.scala:341)
cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:99)
cats.effect.internals.IORunLoop$.start(IORunLoop.scala:35)
cats.effect.IO.unsafeRunAsync(IO.scala:269)
cats.effect.IO.unsafeToFuture(IO.scala:341)
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.$anonfun$applyOrElse$1(MaterializeWorkflowDescriptorActor.scala:152)
scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:206)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:179)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:171)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:670)
	at akka.actor.FSM.processEvent$(FSM.scala:667)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:130)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:806)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:788)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:130)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:664)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:658)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:130)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by aednichols**
Closes #4051 

Also checks for and produces clear errors when tabs and spaces are mixed in a cmd

### CODE REVIEW

File: wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala [hunk 1]
```diff
@@ -10,9 +11,23 @@ object AstToCommandSectionElement {
 
     ast.getAttributeAsVector[CommandPartElement]("parts") map { parts =>
       val lines = makeLines(parts)
-      val trimmed = trimStartAndEnd(lines)
-      val commonPrefixLength = minimumStartLength(trimmed)
-      val commonPrefix = " " * commonPrefixLength
+      val trimmed = trimStartAndEndBlankLines(lines)
+
+      // Commands support either tabs or spaces. For the undefined case of mixed tabs and spaces, Cromwell returns an error.
```
Comment (geoffjentry) [inline wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala]: Why not a warning as per the spec's suggestion?

Comment (aednichols) [reply wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala]: It could be done, but the `stripStarts` function would have to be reworked quite a bit because it currently assumes uniform leading whitespace

I just stopped here because it seemed like the right point along the value <-> effort continuum

File: centaur/src/main/resources/standardTestCases/cmd_whitespace_mixed_same_line.test [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+testFormat: workflowfailure
+
+files {
+  workflow: wdl_draft3/cmd_whitespace/mixed_same_line.wdl
+}
+
+metadata {
+    status: Failed
+    "failures.0.message": "Workflow input processing failed"
+    "failures.0.causedBy.0.message": "Cannot mix leading whitespace characters in command: [\" \", \"\\t\"]"
```
Comment (cjllanwarne) [inline centaur/src/main/resources/standardTestCases/cmd_whitespace_mixed_same_line.test]: We shouldn't need to use centaur integration tests for these, IMO the womtool validation tests are good for validating these "womification time errors"

Comment (aednichols) [reply centaur/src/main/resources/standardTestCases/cmd_whitespace_mixed_same_line.test]: Good tip, thanks.

The womification test harness was not playing well with the exceptions thrown directly in the code, so I took the opportunity to refactor them out of existence.

File: wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala [hunk 3]
```diff
@@ -1,20 +1,44 @@
...
+      // https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#stripping-leading-whitespace
+      val leadingWhitespaceMap = leadingWhitespace(trimmed)
+      val distinctLeadingWhitespaceCharacters = leadingWhitespaceMap.mkString.distinct
+
+      val commonPrefix: Checked[String] = distinctLeadingWhitespaceCharacters.length match {
+        case 0 => "".validNelCheck
+        case 1 =>
+          (distinctLeadingWhitespaceCharacters.head.toString * leadingWhitespaceMap.map(_.length).min).validNelCheck
+        case _ =>
+          s"Cannot mix leading whitespace characters in command: [${distinctLeadingWhitespaceCharacters.map { c: Char =>
```
Comment (cjllanwarne) [inline wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala]: I think perhaps move the `map` outside the interpolation to improve readability?

File: wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala [hunk 4]
```diff
@@ -51,24 +75,29 @@ object AstToCommandSectionElement {
...
+      lines.toList.validNelCheck
+    else
+      (lines map { line =>
+        line.parts.headOption match {
+          case Some(StringCommandPartElement(str)) if str.startsWith(prefix) =>
+            CommandSectionLine(Vector(StringCommandPartElement(str.stripPrefix(prefix))) ++ line.parts.tail).validNelCheck
+          case _ =>
+            "Failed to strip common whitespace prefix from line.".invalidNelCheck
+        }
+      }).toList.sequence[Checked, CommandSectionLine]
```
Comment (cjllanwarne) [inline wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala]: I think `map` + `sequence` = `traverse`, but don't worry too much (especially if intellij has trouble picking up the types)

File: womtool/src/test/resources/validate/wdl_draft3/valid/cmd_whitespace_none/cmd_whitespace_none.wdl [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+  call Echo as echo
+
+}
+
+task Echo {
+
+  runtime { docker: "ubuntu:latest" }
+
+  command {
+echo "I am prefixed with nothing"
```
Comment (cjllanwarne) [inline womtool/src/test/resources/validate/wdl_draft3/valid/cmd_whitespace_none/cmd_whitespace_none.wdl]: Rather than just asserting "passes womification", we might be able to use the `WdlFileToWdlomSpec` to make assertions about what the final command line looks like.

... or even just unit test the `astToCommandSectionElement ` directly to avoid needing a surrounding framework altogether?

Comment (aednichols) [reply womtool/src/test/resources/validate/wdl_draft3/valid/cmd_whitespace_none/cmd_whitespace_none.wdl]: Love the unit test idea, I'm not sure we have any coverage for the whitespace prefix normalization (only `gap_in_command.wdl` for dropping empy lines)

Comment (aednichols) [reply womtool/src/test/resources/validate/wdl_draft3/valid/cmd_whitespace_none/cmd_whitespace_none.wdl]: The idea was much more appealing than reality proved to be; stuck to augmenting `WdlFileToWdlomSpec`
