### PR TITLE
Cromwell 1308 Closes #1308 Closes #1321

### LINKED ISSUE #1308: SFS globbing matches too widely
If an input file matches a glob string, it is also included in the glob output.

This is undesirable

### LINKED ISSUE #1321: Glob grabs incorrect input file (for local and sge backend)
The attached wdl and json file have an issue with the second call in the pipeline. It is scattered over the bam files output by the first call (RevertSam). The problem is that shard-5 grabs the wrong bam file to input into the second call (FirstSortSam). All of the other shards grab the correct file except for shard-5 which grabs the bam file that is the input to the RevertSam task (rather than its output). The workaround to fix this was to change the glob command to be more specific: if I change it from *.bam to *.unmapped.bam, then shard-5 is correct.

[BrokenShard.wdl.txt](https://github.com/broadinstitute/cromwell/files/432898/BrokenShard.wdl.txt)
[testBam.json.txt](https://github.com/broadinstitute/cromwell/files/432900/testBam.json.txt)

Note the example files that are attached need access to the Broad file system to run.

### PR DESCRIPTION
**Pull request by Horneth**
Centaur: https://github.com/broadinstitute/centaur/pull/106

### CODE REVIEW

File: supportedBackends/htcondor/src/test/scala/cromwell/backend/impl/htcondor/HtCondorJobExecutionActorSpec.scala [hunk 1]
```diff
@@ -386,9 +388,9 @@ class HtCondorJobExecutionActorSpec extends TestKitSuite("HtCondorJobExecutionAc
     val bashScript = Source.fromFile(jobPaths.script.toFile).getLines.mkString
 
     assert(bashScript.contains("docker run -w /workingDir -v"))
-    assert(bashScript.contains(tempDir1.toAbsolutePath.toString))
-    assert(bashScript.contains(tempDir2.toAbsolutePath.toString))
-    assert(bashScript.contains("/call-hello:/outputDir --rm ubuntu/latest echo"))
+    assert(bashScript.contains(tempDir1.toAbsolutePath.toString.md5Sum))
```
Comment (cjllanwarne) [inline supportedBackends/htcondor/src/test/scala/cromwell/backend/impl/htcondor/HtCondorJobExecutionActorSpec.scala]: Oh, ha, I made a new one of these implicits for the EngineJobFileHasher, `EngineJobHashingActor.StringMd5er`... I wonder if we can find a better place for them all

File: CHANGELOG.md [hunk 2]
```diff
@@ -42,3 +42,42 @@ to work with various other command line dispatchers such as LSF. See the
...
+    │   ├── rc
+    │   ├── script
+    │   ├── script.background
+    │   ├── script.submit
+    │   ├── stderr
+    │   ├── stderr.background
+    │   ├── stdout
+    │   └── stdout.background
+    └── inputs
+        ├── 2c142eed1d519eabc0520becff443327
```
Comment (cjllanwarne) [inline CHANGELOG.md]: Probably worth a tech talk and/or PO input on the new structure. I can imagine this could be confusing for any spelunking users... @kcibul any thoughts?

**Comment by cjllanwarne** [comment]
Uh, looks like 👍 doesn't work in "review summary" comments... so: 👍 again

File: CHANGELOG.md (hunk 2 above)
Comment (Horneth) [inline CHANGELOG.md]: Yeah I put it in there to see what people think and planned to bring it up at stand up. It personally annoys me to have this nesting so I wanted to give it a try.

Comment (cjllanwarne) [inline CHANGELOG.md]: FWIW I suspect the repeated nesting of directories was also relatively difficult to spelunk(sp?)

File: core/src/main/scala/cromwell/core/PathFactory.scala [hunk 3]
```diff
@@ -4,20 +4,38 @@ import java.io.Writer
...
 import scala.collection.immutable.Queue
-import scala.util.{Success, Try}
+import scala.util.{Success, Failure, Try}
+
+class FileSystemNotFound(str: String) extends CromwellFatalException(
+  new IllegalArgumentException(s"Could not find suitable filesystem to parse $str")
+)
 
 trait PathFactory {
+  private val schemeMatcher = """([a-z]*://).*""".r
```
Comment (mcovarr) [inline core/src/main/scala/cromwell/core/PathFactory.scala]: you probably want `+` and not `*` for at least the first quantifier, maybe the second

File: core/src/main/scala/cromwell/core/PathFactory.scala [hunk 4]
```diff
@@ -4,20 +4,38 @@ import java.io.Writer
...
+          Failure(new IllegalArgumentException(s"$rawString scheme doesn't match ${fs.provider.getScheme}"))
+        } else {
+          Try(fs.getPath(rawString))
+        }
     })
   }
+
+  private def hasWrongScheme(rawString: String, fileSystem: FileSystem): Boolean = {
+    schemeMatcher.findFirstMatchIn(rawString) match {
+      case Some(m) if m.groupCount == 1 => m.group(1) != fileSystem.provider().getScheme
```
Comment (mcovarr) [inline core/src/main/scala/cromwell/core/PathFactory.scala]: the `groupCount` check seems unnecessary, there wouldn't be a match without that group being defined

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala [hunk 5]
```diff
@@ -184,8 +185,9 @@ trait SharedFileSystem extends PathFactory {
     }
 
     def adjustFile(path: String) = {
-      val (src, dst) = toDestPath(path)
-      localize(src, dst) map { Unit => WdlFile(dst.toString) }
+      toDestPath(path) flatMap {
+        case (src, dst) => localize(src, dst) map { Unit => WdlFile(dst.toString) }
```
Comment (mcovarr) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala]: `_` rather than `Unit`

**Comment by geoffjentry** [comment]
I agree w/ the discussion that this requires broader discussion

**Comment by mcovarr** [comment]
:+1:

File: supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala (hunk 5 above)
Comment (geoffjentry) [inline supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala]: Also it's `()` not `Unit`, we've run into issues w/ this before

**Comment by Horneth** [comment]
@geoffjentry All right I'll hold off merging this until we get @kcibul's (also gotc / firecloud ?) opinion.

File: CHANGELOG.md (hunk 2 above)
Comment (kcibul) [inline CHANGELOG.md]: seems reasonable to me.  The only thing would be to not use hashes in the inputs subdirectory, and use some other form of name-shortening (like take the last element of the path plus an incrementing number after 1 like when you download the same file in chrome twice).  

Generally though, I think people don't spelunk as much on inputs as they do on outputs, so this seems fine

Comment (Horneth) [inline CHANGELOG.md]: Just seeing this now for some reason.. The main constraint I think (from an execution standpoint) is that we want input files that originally are in the same directory to end up in the same directory again once localized. I remember having bugs like this before. Let me try with chrome-style naming see how it looks
